// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/stellatune_backend_api/diagnostics/model.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<String> diagnosticsInitialize({required String logDir}) => StellatuneApi
    .instance
    .api
    .crateApiDiagnosticsDiagnosticsInitialize(logDir: logDir);

Future<void> diagnosticsAppend({required List<LogRecord> records}) =>
    StellatuneApi.instance.api.crateApiDiagnosticsDiagnosticsAppend(
      records: records,
    );

Stream<LogBatch> diagnosticsEvents() =>
    StellatuneApi.instance.api.crateApiDiagnosticsDiagnosticsEvents();

Future<List<String>> diagnosticsSessions() =>
    StellatuneApi.instance.api.crateApiDiagnosticsDiagnosticsSessions();

Future<LogPage> diagnosticsQuery({
  required String session,
  required int offset,
  required int limit,
  required String level,
  required String source,
  required String search,
}) => StellatuneApi.instance.api.crateApiDiagnosticsDiagnosticsQuery(
  session: session,
  offset: offset,
  limit: limit,
  level: level,
  source: source,
  search: search,
);

Future<LogRecord> diagnosticsDetail({required String id}) =>
    StellatuneApi.instance.api.crateApiDiagnosticsDiagnosticsDetail(id: id);

Future<void> diagnosticsExport({
  required String session,
  required String destination,
}) => StellatuneApi.instance.api.crateApiDiagnosticsDiagnosticsExport(
  session: session,
  destination: destination,
);

Future<void> diagnosticsFlush() =>
    StellatuneApi.instance.api.crateApiDiagnosticsDiagnosticsFlush();
