// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'dlna/types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<DlnaSsdpDevice>> dlnaDiscoverMediaRenderers({
  required int timeoutMs,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaDiscoverMediaRenderers(
  timeoutMs: timeoutMs,
);

Future<List<DlnaRenderer>> dlnaDiscoverRenderers({required int timeoutMs}) =>
    StellatuneApi.instance.api.crateApiDlnaDlnaDiscoverRenderers(
      timeoutMs: timeoutMs,
    );

Future<DlnaHttpServerInfo> dlnaHttpStart({String? advertiseIp, int? port}) =>
    StellatuneApi.instance.api.crateApiDlnaDlnaHttpStart(
      advertiseIp: advertiseIp,
      port: port,
    );

Future<String> dlnaHttpPublishTrack({required String path}) =>
    StellatuneApi.instance.api.crateApiDlnaDlnaHttpPublishTrack(path: path);

Future<void> dlnaHttpUnpublishAll() =>
    StellatuneApi.instance.api.crateApiDlnaDlnaHttpUnpublishAll();

Future<void> dlnaAvTransportSetUri({
  required String controlUrl,
  String? serviceType,
  required String uri,
  String? metadata,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaAvTransportSetUri(
  controlUrl: controlUrl,
  serviceType: serviceType,
  uri: uri,
  metadata: metadata,
);

Future<void> dlnaAvTransportPlay({
  required String controlUrl,
  String? serviceType,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaAvTransportPlay(
  controlUrl: controlUrl,
  serviceType: serviceType,
);

Future<void> dlnaAvTransportPause({
  required String controlUrl,
  String? serviceType,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaAvTransportPause(
  controlUrl: controlUrl,
  serviceType: serviceType,
);

Future<void> dlnaAvTransportStop({
  required String controlUrl,
  String? serviceType,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaAvTransportStop(
  controlUrl: controlUrl,
  serviceType: serviceType,
);

Future<void> dlnaAvTransportSeekMs({
  required String controlUrl,
  String? serviceType,
  required BigInt positionMs,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaAvTransportSeekMs(
  controlUrl: controlUrl,
  serviceType: serviceType,
  positionMs: positionMs,
);

Future<DlnaTransportInfo> dlnaAvTransportGetTransportInfo({
  required String controlUrl,
  String? serviceType,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaAvTransportGetTransportInfo(
  controlUrl: controlUrl,
  serviceType: serviceType,
);

Future<DlnaPositionInfo> dlnaAvTransportGetPositionInfo({
  required String controlUrl,
  String? serviceType,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaAvTransportGetPositionInfo(
  controlUrl: controlUrl,
  serviceType: serviceType,
);

Future<void> dlnaRenderingControlSetVolume({
  required String controlUrl,
  String? serviceType,
  required int volume0100,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaRenderingControlSetVolume(
  controlUrl: controlUrl,
  serviceType: serviceType,
  volume0100: volume0100,
);

Future<void> dlnaRenderingControlSetMute({
  required String controlUrl,
  String? serviceType,
  required bool mute,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaRenderingControlSetMute(
  controlUrl: controlUrl,
  serviceType: serviceType,
  mute: mute,
);

Future<int> dlnaRenderingControlGetVolume({
  required String controlUrl,
  String? serviceType,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaRenderingControlGetVolume(
  controlUrl: controlUrl,
  serviceType: serviceType,
);

Future<String> dlnaPlayLocalPath({
  required DlnaRenderer renderer,
  required String path,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaPlayLocalPath(
  renderer: renderer,
  path: path,
);

Future<String> dlnaPlayLocalTrack({
  required DlnaRenderer renderer,
  required String path,
  String? title,
  String? artist,
  String? album,
  String? coverPath,
}) => StellatuneApi.instance.api.crateApiDlnaDlnaPlayLocalTrack(
  renderer: renderer,
  path: path,
  title: title,
  artist: artist,
  album: album,
  coverPath: coverPath,
);
