// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `capture`, `message`

class AppError implements FrbException {
  final ErrorCategory category;
  final String operation;
  final String diagnosticId;
  final String fingerprint;
  final String context;

  const AppError({
    required this.category,
    required this.operation,
    required this.diagnosticId,
    required this.fingerprint,
    required this.context,
  });

  @override
  int get hashCode =>
      category.hashCode ^
      operation.hashCode ^
      diagnosticId.hashCode ^
      fingerprint.hashCode ^
      context.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppError &&
          runtimeType == other.runtimeType &&
          category == other.category &&
          operation == other.operation &&
          diagnosticId == other.diagnosticId &&
          fingerprint == other.fingerprint &&
          context == other.context;
}

enum ErrorCategory {
  cancelled,
  unavailable,
  invalidInput,
  notFound,
  timeout,
  unsupported,
  internal,
}
