// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/stellatune_backend_api/lyrics_types.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

@freezed
sealed class LibraryEvent with _$LibraryEvent {
  const LibraryEvent._();

  const factory LibraryEvent.changed() = LibraryEvent_Changed;
  const factory LibraryEvent.scanProgress({
    required PlatformInt64 scanned,
    required PlatformInt64 updated,
    required PlatformInt64 skipped,
    required PlatformInt64 errors,
  }) = LibraryEvent_ScanProgress;
  const factory LibraryEvent.scanFinished({
    required PlatformInt64 durationMs,
    required PlatformInt64 scanned,
    required PlatformInt64 updated,
    required PlatformInt64 skipped,
    required PlatformInt64 errors,
  }) = LibraryEvent_ScanFinished;
  const factory LibraryEvent.error({required AppError error}) =
      LibraryEvent_Error;
  const factory LibraryEvent.log({required String message}) = LibraryEvent_Log;
}

@freezed
sealed class LyricsEvent with _$LyricsEvent {
  const LyricsEvent._();

  const factory LyricsEvent.loading({required String trackKey}) =
      LyricsEvent_Loading;
  const factory LyricsEvent.ready({
    required String trackKey,
    required LyricsDoc doc,
  }) = LyricsEvent_Ready;
  const factory LyricsEvent.cursor({
    required String trackKey,
    required PlatformInt64 lineIndex,
  }) = LyricsEvent_Cursor;
  const factory LyricsEvent.empty({required String trackKey}) =
      LyricsEvent_Empty;
  const factory LyricsEvent.error({
    required String trackKey,
    required AppError error,
  }) = LyricsEvent_Error;
}
