// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/stellatune_core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `shared_library`

Future<void> createLibrary({required String dbPath}) =>
    StellatuneApi.instance.api.crateApiLibraryCreateLibrary(dbPath: dbPath);

Future<void> libraryAddRoot({required String path}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryAddRoot(path: path);

Future<void> libraryRemoveRoot({required String path}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryRemoveRoot(path: path);

Future<void> libraryDeleteFolder({required String path}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryDeleteFolder(path: path);

Future<void> libraryRestoreFolder({required String path}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryRestoreFolder(path: path);

Future<List<String>> libraryListExcludedFolders() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryListExcludedFolders();

Future<void> libraryScanAll() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryScanAll();

Future<void> libraryScanAllForce() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryScanAllForce();

Future<List<String>> libraryListRoots() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryListRoots();

Future<List<String>> libraryListFolders() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryListFolders();

Future<List<TrackLite>> libraryListTracks({
  required String folder,
  required bool recursive,
  required String query,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryListTracks(
  folder: folder,
  recursive: recursive,
  query: query,
  limit: limit,
  offset: offset,
);

Future<List<TrackLite>> librarySearch({
  required String query,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => StellatuneApi.instance.api.crateApiLibraryLibrarySearch(
  query: query,
  limit: limit,
  offset: offset,
);

Future<List<PlaylistLite>> libraryListPlaylists() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryListPlaylists();

Future<void> libraryCreatePlaylist({required String name}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryCreatePlaylist(name: name);

Future<void> libraryRenamePlaylist({
  required PlatformInt64 id,
  required String name,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryRenamePlaylist(
  id: id,
  name: name,
);

Future<void> libraryDeletePlaylist({required PlatformInt64 id}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryDeletePlaylist(id: id);

Future<List<TrackLite>> libraryListPlaylistTracks({
  required PlatformInt64 playlistId,
  required String query,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryListPlaylistTracks(
  playlistId: playlistId,
  query: query,
  limit: limit,
  offset: offset,
);

Future<void> libraryAddTrackToPlaylist({
  required PlatformInt64 playlistId,
  required PlatformInt64 trackId,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryAddTrackToPlaylist(
  playlistId: playlistId,
  trackId: trackId,
);

Future<void> libraryAddTracksToPlaylist({
  required PlatformInt64 playlistId,
  required Int64List trackIds,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryAddTracksToPlaylist(
  playlistId: playlistId,
  trackIds: trackIds,
);

Future<void> libraryRemoveTrackFromPlaylist({
  required PlatformInt64 playlistId,
  required PlatformInt64 trackId,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryRemoveTrackFromPlaylist(
  playlistId: playlistId,
  trackId: trackId,
);

Future<void> libraryRemoveTracksFromPlaylist({
  required PlatformInt64 playlistId,
  required Int64List trackIds,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryRemoveTracksFromPlaylist(
  playlistId: playlistId,
  trackIds: trackIds,
);

Future<void> libraryMoveTrackInPlaylist({
  required PlatformInt64 playlistId,
  required PlatformInt64 trackId,
  required PlatformInt64 newIndex,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryMoveTrackInPlaylist(
  playlistId: playlistId,
  trackId: trackId,
  newIndex: newIndex,
);

Future<Int64List> libraryListLikedTrackIds() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryListLikedTrackIds();

Future<void> librarySetTrackLiked({
  required PlatformInt64 trackId,
  required bool liked,
}) => StellatuneApi.instance.api.crateApiLibraryLibrarySetTrackLiked(
  trackId: trackId,
  liked: liked,
);

Stream<LibraryEvent> libraryEvents() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryEvents();

Future<void> libraryPluginDisable({required String pluginId}) => StellatuneApi
    .instance
    .api
    .crateApiLibraryLibraryPluginDisable(pluginId: pluginId);

Future<void> libraryPluginEnable({required String pluginId}) => StellatuneApi
    .instance
    .api
    .crateApiLibraryLibraryPluginEnable(pluginId: pluginId);

Future<void> libraryPluginApplyState() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryPluginApplyState();

Future<String> libraryPluginApplyStateStatusJson() => StellatuneApi.instance.api
    .crateApiLibraryLibraryPluginApplyStateStatusJson();

Future<List<String>> libraryListDisabledPluginIds() =>
    StellatuneApi.instance.api.crateApiLibraryLibraryListDisabledPluginIds();
