// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/stellatune_core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`

Future<Library> createLibrary({required String dbPath}) =>
    StellatuneApi.instance.api.crateApiLibraryCreateLibrary(dbPath: dbPath);

Future<void> libraryAddRoot({
  required Library library_,
  required String path,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryAddRoot(
  library_: library_,
  path: path,
);

Future<void> libraryRemoveRoot({
  required Library library_,
  required String path,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryRemoveRoot(
  library_: library_,
  path: path,
);

Future<void> libraryDeleteFolder({
  required Library library_,
  required String path,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryDeleteFolder(
  library_: library_,
  path: path,
);

Future<void> libraryRestoreFolder({
  required Library library_,
  required String path,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryRestoreFolder(
  library_: library_,
  path: path,
);

Future<void> libraryListExcludedFolders({required Library library_}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryListExcludedFolders(
      library_: library_,
    );

Future<void> libraryScanAll({required Library library_}) => StellatuneApi
    .instance
    .api
    .crateApiLibraryLibraryScanAll(library_: library_);

Future<void> libraryScanAllForce({required Library library_}) => StellatuneApi
    .instance
    .api
    .crateApiLibraryLibraryScanAllForce(library_: library_);

Future<void> libraryListRoots({required Library library_}) => StellatuneApi
    .instance
    .api
    .crateApiLibraryLibraryListRoots(library_: library_);

Future<void> libraryListFolders({required Library library_}) => StellatuneApi
    .instance
    .api
    .crateApiLibraryLibraryListFolders(library_: library_);

Future<void> libraryListTracks({
  required Library library_,
  required String folder,
  required bool recursive,
  required String query,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryListTracks(
  library_: library_,
  folder: folder,
  recursive: recursive,
  query: query,
  limit: limit,
  offset: offset,
);

Future<void> librarySearch({
  required Library library_,
  required String query,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => StellatuneApi.instance.api.crateApiLibraryLibrarySearch(
  library_: library_,
  query: query,
  limit: limit,
  offset: offset,
);

Future<void> libraryListPlaylists({required Library library_}) => StellatuneApi
    .instance
    .api
    .crateApiLibraryLibraryListPlaylists(library_: library_);

Future<void> libraryCreatePlaylist({
  required Library library_,
  required String name,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryCreatePlaylist(
  library_: library_,
  name: name,
);

Future<void> libraryRenamePlaylist({
  required Library library_,
  required PlatformInt64 id,
  required String name,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryRenamePlaylist(
  library_: library_,
  id: id,
  name: name,
);

Future<void> libraryDeletePlaylist({
  required Library library_,
  required PlatformInt64 id,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryDeletePlaylist(
  library_: library_,
  id: id,
);

Future<void> libraryListPlaylistTracks({
  required Library library_,
  required PlatformInt64 playlistId,
  required String query,
  required PlatformInt64 limit,
  required PlatformInt64 offset,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryListPlaylistTracks(
  library_: library_,
  playlistId: playlistId,
  query: query,
  limit: limit,
  offset: offset,
);

Future<void> libraryAddTrackToPlaylist({
  required Library library_,
  required PlatformInt64 playlistId,
  required PlatformInt64 trackId,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryAddTrackToPlaylist(
  library_: library_,
  playlistId: playlistId,
  trackId: trackId,
);

Future<void> libraryAddTracksToPlaylist({
  required Library library_,
  required PlatformInt64 playlistId,
  required Int64List trackIds,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryAddTracksToPlaylist(
  library_: library_,
  playlistId: playlistId,
  trackIds: trackIds,
);

Future<void> libraryRemoveTrackFromPlaylist({
  required Library library_,
  required PlatformInt64 playlistId,
  required PlatformInt64 trackId,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryRemoveTrackFromPlaylist(
  library_: library_,
  playlistId: playlistId,
  trackId: trackId,
);

Future<void> libraryRemoveTracksFromPlaylist({
  required Library library_,
  required PlatformInt64 playlistId,
  required Int64List trackIds,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryRemoveTracksFromPlaylist(
  library_: library_,
  playlistId: playlistId,
  trackIds: trackIds,
);

Future<void> libraryMoveTrackInPlaylist({
  required Library library_,
  required PlatformInt64 playlistId,
  required PlatformInt64 trackId,
  required PlatformInt64 newIndex,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryMoveTrackInPlaylist(
  library_: library_,
  playlistId: playlistId,
  trackId: trackId,
  newIndex: newIndex,
);

Future<void> libraryListLikedTrackIds({required Library library_}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryListLikedTrackIds(
      library_: library_,
    );

Future<void> librarySetTrackLiked({
  required Library library_,
  required PlatformInt64 trackId,
  required bool liked,
}) => StellatuneApi.instance.api.crateApiLibraryLibrarySetTrackLiked(
  library_: library_,
  trackId: trackId,
  liked: liked,
);

Stream<LibraryEvent> libraryEvents({required Library library_}) =>
    StellatuneApi.instance.api.crateApiLibraryLibraryEvents(library_: library_);

Future<void> libraryPluginDisable({
  required Library library_,
  required String pluginId,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryPluginDisable(
  library_: library_,
  pluginId: pluginId,
);

Future<void> libraryPluginEnable({
  required Library library_,
  required String pluginId,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryPluginEnable(
  library_: library_,
  pluginId: pluginId,
);

Future<void> libraryPluginsReloadFromState({
  required Library library_,
  required String dir,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryPluginsReloadFromState(
  library_: library_,
  dir: dir,
);

Future<List<String>> libraryListDisabledPluginIds({
  required Library library_,
}) => StellatuneApi.instance.api.crateApiLibraryLibraryListDisabledPluginIds(
  library_: library_,
);

// Rust type: RustOpaqueMoi<Library>
abstract class Library implements RustOpaqueInterface {}
