// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/stellatune_library/catalog.dart';
import 'error.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `service`

Future<List<LibrarySource>> catalogListSources() =>
    StellatuneApi.instance.api.crateApiMediaCatalogCatalogListSources();

Future<CatalogPage> catalogBrowse({required CatalogQuery query}) =>
    StellatuneApi.instance.api.crateApiMediaCatalogCatalogBrowse(query: query);

Future<CatalogItem> catalogGetDetail({required MediaRef reference}) =>
    StellatuneApi.instance.api.crateApiMediaCatalogCatalogGetDetail(
      reference: reference,
    );

Future<Uint64List> catalogPrepareTracks({required List<CatalogItem> items}) =>
    StellatuneApi.instance.api.crateApiMediaCatalogCatalogPrepareTracks(
      items: items,
    );

Future<List<CatalogItem>> catalogCollectTracks({
  required CatalogQuery query,
  required String requestId,
}) => StellatuneApi.instance.api.crateApiMediaCatalogCatalogCollectTracks(
  query: query,
  requestId: requestId,
);

Future<void> catalogCancelCollection({required String requestId}) =>
    StellatuneApi.instance.api.crateApiMediaCatalogCatalogCancelCollection(
      requestId: requestId,
    );
