// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/stellatune_core.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `new`

Future<Player> createPlayer() =>
    StellatuneApi.instance.api.crateApiPlayerCreatePlayer();

Future<void> disposePlayer({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerDisposePlayer(player: player);

Future<void> switchTrackRef({
  required Player player,
  required TrackRef track,
  required bool lazy,
}) => StellatuneApi.instance.api.crateApiPlayerSwitchTrackRef(
  player: player,
  track: track,
  lazy: lazy,
);

Future<void> play({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerPlay(player: player);

Future<void> pause({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerPause(player: player);

Future<void> seekMs({required Player player, required BigInt positionMs}) =>
    StellatuneApi.instance.api.crateApiPlayerSeekMs(
      player: player,
      positionMs: positionMs,
    );

Future<void> setVolume({required Player player, required double volume}) =>
    StellatuneApi.instance.api.crateApiPlayerSetVolume(
      player: player,
      volume: volume,
    );

Future<void> stop({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerStop(player: player);

Stream<Event> events({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerEvents(player: player);

Stream<PluginRuntimeEvent> pluginRuntimeEventsGlobal() =>
    StellatuneApi.instance.api.crateApiPlayerPluginRuntimeEventsGlobal();

Future<void> lyricsPrepare({
  required Player player,
  required LyricsQuery query,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsPrepare(
  player: player,
  query: query,
);

Future<void> lyricsPrefetch({
  required Player player,
  required LyricsQuery query,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsPrefetch(
  player: player,
  query: query,
);

Future<List<LyricsSearchCandidate>> lyricsSearchCandidates({
  required Player player,
  required LyricsQuery query,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsSearchCandidates(
  player: player,
  query: query,
);

Future<void> lyricsApplyCandidate({
  required Player player,
  required String trackKey,
  required LyricsDoc doc,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsApplyCandidate(
  player: player,
  trackKey: trackKey,
  doc: doc,
);

Future<void> lyricsSetCacheDbPath({
  required Player player,
  required String dbPath,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsSetCacheDbPath(
  player: player,
  dbPath: dbPath,
);

Future<void> lyricsClearCache({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerLyricsClearCache(player: player);

Future<void> lyricsRefreshCurrent({required Player player}) => StellatuneApi
    .instance
    .api
    .crateApiPlayerLyricsRefreshCurrent(player: player);

Future<void> lyricsSetPositionMs({
  required Player player,
  required BigInt positionMs,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsSetPositionMs(
  player: player,
  positionMs: positionMs,
);

Stream<LyricsEvent> lyricsEvents({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerLyricsEvents(player: player);

Future<List<PluginDescriptor>> pluginsList({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerPluginsList(player: player);

Future<void> pluginPublishEventJson({
  required Player player,
  String? pluginId,
  required String eventJson,
}) => StellatuneApi.instance.api.crateApiPlayerPluginPublishEventJson(
  player: player,
  pluginId: pluginId,
  eventJson: eventJson,
);

Future<List<DspTypeDescriptor>> dspListTypes({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerDspListTypes(player: player);

Future<List<SourceCatalogTypeDescriptor>> sourceListTypes({
  required Player player,
}) => StellatuneApi.instance.api.crateApiPlayerSourceListTypes(player: player);

Future<List<LyricsProviderTypeDescriptor>> lyricsProviderListTypes({
  required Player player,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsProviderListTypes(
  player: player,
);

Future<List<OutputSinkTypeDescriptor>> outputSinkListTypes({
  required Player player,
}) => StellatuneApi.instance.api.crateApiPlayerOutputSinkListTypes(
  player: player,
);

Future<String> sourceListItemsJson({
  required Player player,
  required String pluginId,
  required String typeId,
  required String configJson,
  required String requestJson,
}) => StellatuneApi.instance.api.crateApiPlayerSourceListItemsJson(
  player: player,
  pluginId: pluginId,
  typeId: typeId,
  configJson: configJson,
  requestJson: requestJson,
);

Future<String> lyricsProviderSearchJson({
  required Player player,
  required String pluginId,
  required String typeId,
  required String queryJson,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsProviderSearchJson(
  player: player,
  pluginId: pluginId,
  typeId: typeId,
  queryJson: queryJson,
);

Future<String> lyricsProviderFetchJson({
  required Player player,
  required String pluginId,
  required String typeId,
  required String trackJson,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsProviderFetchJson(
  player: player,
  pluginId: pluginId,
  typeId: typeId,
  trackJson: trackJson,
);

Future<String> outputSinkListTargetsJson({
  required Player player,
  required String pluginId,
  required String typeId,
  required String configJson,
}) => StellatuneApi.instance.api.crateApiPlayerOutputSinkListTargetsJson(
  player: player,
  pluginId: pluginId,
  typeId: typeId,
  configJson: configJson,
);

Future<void> dspSetChain({
  required Player player,
  required List<DspChainItem> chain,
}) => StellatuneApi.instance.api.crateApiPlayerDspSetChain(
  player: player,
  chain: chain,
);

Future<TrackDecodeInfo?> currentTrackInfo({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerCurrentTrackInfo(player: player);

Future<void> pluginsReload({required Player player, required String dir}) =>
    StellatuneApi.instance.api.crateApiPlayerPluginsReload(
      player: player,
      dir: dir,
    );

Future<String> pluginsInstallFromFile({
  required String pluginsDir,
  required String artifactPath,
}) => StellatuneApi.instance.api.crateApiPlayerPluginsInstallFromFile(
  pluginsDir: pluginsDir,
  artifactPath: artifactPath,
);

Future<String> pluginsListInstalledJson({required String pluginsDir}) =>
    StellatuneApi.instance.api.crateApiPlayerPluginsListInstalledJson(
      pluginsDir: pluginsDir,
    );

Future<void> pluginsUninstallById({
  required String pluginsDir,
  required String pluginId,
}) => StellatuneApi.instance.api.crateApiPlayerPluginsUninstallById(
  pluginsDir: pluginsDir,
  pluginId: pluginId,
);

Future<void> refreshDevices({required Player player}) =>
    StellatuneApi.instance.api.crateApiPlayerRefreshDevices(player: player);

Future<void> setOutputDevice({
  required Player player,
  required AudioBackend backend,
  String? deviceId,
}) => StellatuneApi.instance.api.crateApiPlayerSetOutputDevice(
  player: player,
  backend: backend,
  deviceId: deviceId,
);

Future<void> setOutputOptions({
  required Player player,
  required bool matchTrackSampleRate,
  required bool gaplessPlayback,
  required bool seekTrackFade,
}) => StellatuneApi.instance.api.crateApiPlayerSetOutputOptions(
  player: player,
  matchTrackSampleRate: matchTrackSampleRate,
  gaplessPlayback: gaplessPlayback,
  seekTrackFade: seekTrackFade,
);

Future<void> setOutputSinkRoute({
  required Player player,
  required OutputSinkRoute route,
}) => StellatuneApi.instance.api.crateApiPlayerSetOutputSinkRoute(
  player: player,
  route: route,
);

Future<void> clearOutputSinkRoute({required Player player}) => StellatuneApi
    .instance
    .api
    .crateApiPlayerClearOutputSinkRoute(player: player);

Future<void> preloadTrack({
  required Player player,
  required String path,
  required BigInt positionMs,
}) => StellatuneApi.instance.api.crateApiPlayerPreloadTrack(
  player: player,
  path: path,
  positionMs: positionMs,
);

Future<void> preloadTrackRef({
  required Player player,
  required TrackRef track,
  required BigInt positionMs,
}) => StellatuneApi.instance.api.crateApiPlayerPreloadTrackRef(
  player: player,
  track: track,
  positionMs: positionMs,
);

Future<List<TrackPlayability>> canPlayTrackRefs({
  required Player player,
  required List<TrackRef> tracks,
}) => StellatuneApi.instance.api.crateApiPlayerCanPlayTrackRefs(
  player: player,
  tracks: tracks,
);

// Rust type: RustOpaqueMoi<Player>
abstract class Player implements RustOpaqueInterface {}
