// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../third_party/stellatune_backend_api/lyrics_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'player/types.dart';

// These functions are ignored because they are not marked as `pub`: `clear_cached_track_info`, `clear_pending_preload_seek`, `decode_track_token_path`, `encode_track_ref_token`, `engine`, `extract_lyrics_fetch_id`, `extract_lyrics_search_keyword`, `lyrics`, `map_lfe_mode`, `map_player_state`, `map_resample_quality`, `map_v2_event_to_ffi`, `next_position_session_id`, `normalize_json_payload`, `normalize_json_string_payload`, `set_pending_preload_seek`, `shared_player_context`, `take_pending_preload_seek_for_event`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedTrackDecodeInfo`, `FfiEventMapperState`, `PendingPreloadSeek`, `PlayerContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`
// These functions are ignored (category: IgnoreBecauseOwnerTyShouldIgnore): `default`

Future<void> switchTrackRef({required TrackRef track, required bool lazy}) =>
    StellatuneApi.instance.api.crateApiPlayerSwitchTrackRef(
      track: track,
      lazy: lazy,
    );

Future<void> play() => StellatuneApi.instance.api.crateApiPlayerPlay();

Future<void> pause() => StellatuneApi.instance.api.crateApiPlayerPause();

Future<void> seekMs({required BigInt positionMs}) =>
    StellatuneApi.instance.api.crateApiPlayerSeekMs(positionMs: positionMs);

Future<void> setVolume({
  required double volume,
  required BigInt seq,
  required int rampMs,
}) => StellatuneApi.instance.api.crateApiPlayerSetVolume(
  volume: volume,
  seq: seq,
  rampMs: rampMs,
);

Future<void> setLfeMode({required LfeMode mode}) =>
    StellatuneApi.instance.api.crateApiPlayerSetLfeMode(mode: mode);

Future<void> stop() => StellatuneApi.instance.api.crateApiPlayerStop();

Stream<Event> events() => StellatuneApi.instance.api.crateApiPlayerEvents();

Stream<PluginRuntimeEvent> pluginRuntimeEventsGlobal() =>
    StellatuneApi.instance.api.crateApiPlayerPluginRuntimeEventsGlobal();

Future<void> lyricsPrepare({required LyricsQuery query}) =>
    StellatuneApi.instance.api.crateApiPlayerLyricsPrepare(query: query);

Future<void> lyricsPrefetch({required LyricsQuery query}) =>
    StellatuneApi.instance.api.crateApiPlayerLyricsPrefetch(query: query);

Future<List<LyricsSearchCandidate>> lyricsSearchCandidates({
  required LyricsQuery query,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsSearchCandidates(
  query: query,
);

Future<void> lyricsApplyCandidate({
  required String trackKey,
  required LyricsDoc doc,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsApplyCandidate(
  trackKey: trackKey,
  doc: doc,
);

Future<void> lyricsSetCacheDbPath({required String dbPath}) => StellatuneApi
    .instance
    .api
    .crateApiPlayerLyricsSetCacheDbPath(dbPath: dbPath);

Future<void> lyricsClearCache() =>
    StellatuneApi.instance.api.crateApiPlayerLyricsClearCache();

Future<void> lyricsRefreshCurrent() =>
    StellatuneApi.instance.api.crateApiPlayerLyricsRefreshCurrent();

Future<void> lyricsSetPositionMs({required BigInt positionMs}) => StellatuneApi
    .instance
    .api
    .crateApiPlayerLyricsSetPositionMs(positionMs: positionMs);

Stream<LyricsEvent> lyricsEvents() =>
    StellatuneApi.instance.api.crateApiPlayerLyricsEvents();

Future<List<PluginDescriptor>> pluginsList() =>
    StellatuneApi.instance.api.crateApiPlayerPluginsList();

Future<void> pluginPublishEventJson({
  String? pluginId,
  required String eventJson,
}) => StellatuneApi.instance.api.crateApiPlayerPluginPublishEventJson(
  pluginId: pluginId,
  eventJson: eventJson,
);

Future<List<DspTypeDescriptor>> dspListTypes() =>
    StellatuneApi.instance.api.crateApiPlayerDspListTypes();

Future<List<SourceCatalogTypeDescriptor>> sourceListTypes() =>
    StellatuneApi.instance.api.crateApiPlayerSourceListTypes();

Future<List<LyricsProviderTypeDescriptor>> lyricsProviderListTypes() =>
    StellatuneApi.instance.api.crateApiPlayerLyricsProviderListTypes();

Future<List<OutputSinkTypeDescriptor>> outputSinkListTypes() =>
    StellatuneApi.instance.api.crateApiPlayerOutputSinkListTypes();

Future<String> sourceListItemsJson({
  required String pluginId,
  required String typeId,
  required String configJson,
  required String requestJson,
}) => StellatuneApi.instance.api.crateApiPlayerSourceListItemsJson(
  pluginId: pluginId,
  typeId: typeId,
  configJson: configJson,
  requestJson: requestJson,
);

Future<String> lyricsProviderSearchJson({
  required String pluginId,
  required String typeId,
  required String queryJson,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsProviderSearchJson(
  pluginId: pluginId,
  typeId: typeId,
  queryJson: queryJson,
);

Future<String> lyricsProviderFetchJson({
  required String pluginId,
  required String typeId,
  required String trackJson,
}) => StellatuneApi.instance.api.crateApiPlayerLyricsProviderFetchJson(
  pluginId: pluginId,
  typeId: typeId,
  trackJson: trackJson,
);

Future<String> outputSinkListTargetsJson({
  required String pluginId,
  required String typeId,
  required String configJson,
}) => StellatuneApi.instance.api.crateApiPlayerOutputSinkListTargetsJson(
  pluginId: pluginId,
  typeId: typeId,
  configJson: configJson,
);

Future<void> dspSetChain({required List<DspChainItem> chain}) =>
    StellatuneApi.instance.api.crateApiPlayerDspSetChain(chain: chain);

Future<TrackDecodeInfo?> currentTrackInfo() =>
    StellatuneApi.instance.api.crateApiPlayerCurrentTrackInfo();

Future<String> pluginsInstallFromFile({
  required String pluginsDir,
  required String artifactPath,
}) => StellatuneApi.instance.api.crateApiPlayerPluginsInstallFromFile(
  pluginsDir: pluginsDir,
  artifactPath: artifactPath,
);

Future<String> pluginsListInstalledJson({required String pluginsDir}) =>
    StellatuneApi.instance.api.crateApiPlayerPluginsListInstalledJson(
      pluginsDir: pluginsDir,
    );

Future<void> pluginsUninstallById({
  required String pluginsDir,
  required String pluginId,
}) => StellatuneApi.instance.api.crateApiPlayerPluginsUninstallById(
  pluginsDir: pluginsDir,
  pluginId: pluginId,
);

Future<List<AudioDevice>> refreshDevices() =>
    StellatuneApi.instance.api.crateApiPlayerRefreshDevices();

Future<void> setOutputDevice({
  required AudioBackend backend,
  String? deviceId,
}) => StellatuneApi.instance.api.crateApiPlayerSetOutputDevice(
  backend: backend,
  deviceId: deviceId,
);

Future<void> setOutputOptions({
  required bool matchTrackSampleRate,
  required bool gaplessPlayback,
  required bool seekTrackFade,
  required ResampleQuality resampleQuality,
}) => StellatuneApi.instance.api.crateApiPlayerSetOutputOptions(
  matchTrackSampleRate: matchTrackSampleRate,
  gaplessPlayback: gaplessPlayback,
  seekTrackFade: seekTrackFade,
  resampleQuality: resampleQuality,
);

Future<void> setOutputSinkRoute({required OutputSinkRoute route}) =>
    StellatuneApi.instance.api.crateApiPlayerSetOutputSinkRoute(route: route);

Future<void> clearOutputSinkRoute() =>
    StellatuneApi.instance.api.crateApiPlayerClearOutputSinkRoute();

Future<void> preloadTrack({required String path, required BigInt positionMs}) =>
    StellatuneApi.instance.api.crateApiPlayerPreloadTrack(
      path: path,
      positionMs: positionMs,
    );

Future<void> preloadTrackRef({
  required TrackRef track,
  required BigInt positionMs,
}) => StellatuneApi.instance.api.crateApiPlayerPreloadTrackRef(
  track: track,
  positionMs: positionMs,
);

Future<List<String>> decoderSupportedExtensions() =>
    StellatuneApi.instance.api.crateApiPlayerDecoderSupportedExtensions();
