// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/stellatune_core.dart';

// These functions are ignored because they are not marked as `pub`: `new`

Future<CoreService> createCoreService() =>
    StellatuneApi.instance.api.crateApiCreateCoreService();

Future<void> sendCommand({
  required CoreService service,
  required Command cmd,
}) =>
    StellatuneApi.instance.api.crateApiSendCommand(service: service, cmd: cmd);

Stream<Event> eventsStream({required CoreService service}) =>
    StellatuneApi.instance.api.crateApiEventsStream(service: service);

// Rust type: RustOpaqueMoi<CoreService>
abstract class CoreService implements RustOpaqueInterface {}
