// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/stellatune_core.dart';

/// Main entrypoint of the Rust API
class StellatuneApi
    extends
        BaseEntrypoint<
          StellatuneApiApi,
          StellatuneApiApiImpl,
          StellatuneApiWire
        > {
  @internal
  static final instance = StellatuneApi._();

  StellatuneApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    StellatuneApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required StellatuneApiApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<StellatuneApiApiImpl, StellatuneApiWire>
  get apiImplConstructor => StellatuneApiApiImpl.new;

  @override
  WireConstructor<StellatuneApiWire> get wireConstructor =>
      StellatuneApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1451320472;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'stellatune_ffi',
        ioDirectory: '../../crates/stellatune-ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class StellatuneApiApi extends BaseApi {
  Future<Library> crateApiCreateLibrary({required String dbPath});

  Future<Player> crateApiCreatePlayer();

  Stream<Event> crateApiEvents({required Player player});

  Future<void> crateApiLibraryAddRoot({
    required Library library_,
    required String path,
  });

  Future<void> crateApiLibraryDeleteFolder({
    required Library library_,
    required String path,
  });

  Stream<LibraryEvent> crateApiLibraryEvents({required Library library_});

  Future<void> crateApiLibraryListExcludedFolders({required Library library_});

  Future<void> crateApiLibraryListFolders({required Library library_});

  Future<void> crateApiLibraryListRoots({required Library library_});

  Future<void> crateApiLibraryListTracks({
    required Library library_,
    required String folder,
    required bool recursive,
    required String query,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  Future<void> crateApiLibraryRemoveRoot({
    required Library library_,
    required String path,
  });

  Future<void> crateApiLibraryRestoreFolder({
    required Library library_,
    required String path,
  });

  Future<void> crateApiLibraryScanAll({required Library library_});

  Future<void> crateApiLibrarySearch({
    required Library library_,
    required String query,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  });

  Future<void> crateApiLoad({required Player player, required String path});

  Future<void> crateApiPause({required Player player});

  Future<void> crateApiPlay({required Player player});

  Future<void> crateApiStop({required Player player});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Library;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Library;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LibraryPtr;

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Player;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Player;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PlayerPtr;
}

class StellatuneApiApiImpl extends StellatuneApiApiImplPlatform
    implements StellatuneApiApi {
  StellatuneApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Library> crateApiCreateLibrary({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_RustOpaque_Library,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiCreateLibraryConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateLibraryConstMeta =>
      const TaskConstMeta(debugName: "create_library", argNames: ["dbPath"]);

  @override
  Future<Player> crateApiCreatePlayer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_RustOpaque_Player,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreatePlayerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreatePlayerConstMeta =>
      const TaskConstMeta(debugName: "create_player", argNames: []);

  @override
  Stream<Event> crateApiEvents({required Player player}) {
    final sink = RustStreamSink<Event>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_RustOpaque_Player(player, serializer);
            sse_encode_StreamSink_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 3,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEventsConstMeta,
          argValues: [player, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEventsConstMeta =>
      const TaskConstMeta(debugName: "events", argNames: ["player", "sink"]);

  @override
  Future<void> crateApiLibraryAddRoot({
    required Library library_,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryAddRootConstMeta,
        argValues: [library_, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryAddRootConstMeta => const TaskConstMeta(
    debugName: "library_add_root",
    argNames: ["library_", "path"],
  );

  @override
  Future<void> crateApiLibraryDeleteFolder({
    required Library library_,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryDeleteFolderConstMeta,
        argValues: [library_, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryDeleteFolderConstMeta =>
      const TaskConstMeta(
        debugName: "library_delete_folder",
        argNames: ["library_", "path"],
      );

  @override
  Stream<LibraryEvent> crateApiLibraryEvents({required Library library_}) {
    final sink = RustStreamSink<LibraryEvent>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_RustOpaque_Library(library_, serializer);
            sse_encode_StreamSink_library_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 6,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiLibraryEventsConstMeta,
          argValues: [library_, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiLibraryEventsConstMeta => const TaskConstMeta(
    debugName: "library_events",
    argNames: ["library_", "sink"],
  );

  @override
  Future<void> crateApiLibraryListExcludedFolders({required Library library_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryListExcludedFoldersConstMeta,
        argValues: [library_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListExcludedFoldersConstMeta =>
      const TaskConstMeta(
        debugName: "library_list_excluded_folders",
        argNames: ["library_"],
      );

  @override
  Future<void> crateApiLibraryListFolders({required Library library_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryListFoldersConstMeta,
        argValues: [library_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListFoldersConstMeta => const TaskConstMeta(
    debugName: "library_list_folders",
    argNames: ["library_"],
  );

  @override
  Future<void> crateApiLibraryListRoots({required Library library_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryListRootsConstMeta,
        argValues: [library_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListRootsConstMeta => const TaskConstMeta(
    debugName: "library_list_roots",
    argNames: ["library_"],
  );

  @override
  Future<void> crateApiLibraryListTracks({
    required Library library_,
    required String folder,
    required bool recursive,
    required String query,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          sse_encode_String(folder, serializer);
          sse_encode_bool(recursive, serializer);
          sse_encode_String(query, serializer);
          sse_encode_i_64(limit, serializer);
          sse_encode_i_64(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryListTracksConstMeta,
        argValues: [library_, folder, recursive, query, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryListTracksConstMeta => const TaskConstMeta(
    debugName: "library_list_tracks",
    argNames: ["library_", "folder", "recursive", "query", "limit", "offset"],
  );

  @override
  Future<void> crateApiLibraryRemoveRoot({
    required Library library_,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryRemoveRootConstMeta,
        argValues: [library_, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryRemoveRootConstMeta => const TaskConstMeta(
    debugName: "library_remove_root",
    argNames: ["library_", "path"],
  );

  @override
  Future<void> crateApiLibraryRestoreFolder({
    required Library library_,
    required String path,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryRestoreFolderConstMeta,
        argValues: [library_, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryRestoreFolderConstMeta =>
      const TaskConstMeta(
        debugName: "library_restore_folder",
        argNames: ["library_", "path"],
      );

  @override
  Future<void> crateApiLibraryScanAll({required Library library_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibraryScanAllConstMeta,
        argValues: [library_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryScanAllConstMeta => const TaskConstMeta(
    debugName: "library_scan_all",
    argNames: ["library_"],
  );

  @override
  Future<void> crateApiLibrarySearch({
    required Library library_,
    required String query,
    required PlatformInt64 limit,
    required PlatformInt64 offset,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Library(library_, serializer);
          sse_encode_String(query, serializer);
          sse_encode_i_64(limit, serializer);
          sse_encode_i_64(offset, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLibrarySearchConstMeta,
        argValues: [library_, query, limit, offset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibrarySearchConstMeta => const TaskConstMeta(
    debugName: "library_search",
    argNames: ["library_", "query", "limit", "offset"],
  );

  @override
  Future<void> crateApiLoad({required Player player, required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Player(player, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoadConstMeta,
        argValues: [player, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadConstMeta =>
      const TaskConstMeta(debugName: "load", argNames: ["player", "path"]);

  @override
  Future<void> crateApiPause({required Player player}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Player(player, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPauseConstMeta,
        argValues: [player],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPauseConstMeta =>
      const TaskConstMeta(debugName: "pause", argNames: ["player"]);

  @override
  Future<void> crateApiPlay({required Player player}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Player(player, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayConstMeta,
        argValues: [player],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayConstMeta =>
      const TaskConstMeta(debugName: "play", argNames: ["player"]);

  @override
  Future<void> crateApiStop({required Player player}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Player(player, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStopConstMeta,
        argValues: [player],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopConstMeta =>
      const TaskConstMeta(debugName: "stop", argNames: ["player"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Library =>
      wire.rust_arc_increment_strong_count_RustOpaque_Library;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Library =>
      wire.rust_arc_decrement_strong_count_RustOpaque_Library;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Player =>
      wire.rust_arc_increment_strong_count_RustOpaque_Player;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Player =>
      wire.rust_arc_decrement_strong_count_RustOpaque_Player;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Library dco_decode_RustOpaque_Library(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return LibraryImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  Player dco_decode_RustOpaque_Player(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<Event> dco_decode_StreamSink_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<LibraryEvent> dco_decode_StreamSink_library_event_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  Event dco_decode_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Event_StateChanged(state: dco_decode_player_state(raw[1]));
      case 1:
        return Event_Position(ms: dco_decode_i_64(raw[1]));
      case 2:
        return Event_TrackChanged(path: dco_decode_String(raw[1]));
      case 3:
        return Event_PlaybackEnded(path: dco_decode_String(raw[1]));
      case 4:
        return Event_Error(message: dco_decode_String(raw[1]));
      case 5:
        return Event_Log(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LibraryEvent dco_decode_library_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return LibraryEvent_Roots(paths: dco_decode_list_String(raw[1]));
      case 1:
        return LibraryEvent_Folders(paths: dco_decode_list_String(raw[1]));
      case 2:
        return LibraryEvent_ExcludedFolders(
          paths: dco_decode_list_String(raw[1]),
        );
      case 3:
        return LibraryEvent_Changed();
      case 4:
        return LibraryEvent_Tracks(
          folder: dco_decode_String(raw[1]),
          recursive: dco_decode_bool(raw[2]),
          query: dco_decode_String(raw[3]),
          items: dco_decode_list_track_lite(raw[4]),
        );
      case 5:
        return LibraryEvent_ScanProgress(
          scanned: dco_decode_i_64(raw[1]),
          updated: dco_decode_i_64(raw[2]),
          skipped: dco_decode_i_64(raw[3]),
          errors: dco_decode_i_64(raw[4]),
        );
      case 6:
        return LibraryEvent_ScanFinished(
          durationMs: dco_decode_i_64(raw[1]),
          scanned: dco_decode_i_64(raw[2]),
          updated: dco_decode_i_64(raw[3]),
          skipped: dco_decode_i_64(raw[4]),
          errors: dco_decode_i_64(raw[5]),
        );
      case 7:
        return LibraryEvent_SearchResult(
          query: dco_decode_String(raw[1]),
          items: dco_decode_list_track_lite(raw[2]),
        );
      case 8:
        return LibraryEvent_Error(message: dco_decode_String(raw[1]));
      case 9:
        return LibraryEvent_Log(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TrackLite> dco_decode_list_track_lite(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_track_lite).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  PlayerState dco_decode_player_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerState.values[raw as int];
  }

  @protected
  TrackLite dco_decode_track_lite(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return TrackLite(
      id: dco_decode_i_64(arr[0]),
      path: dco_decode_String(arr[1]),
      title: dco_decode_opt_String(arr[2]),
      artist: dco_decode_opt_String(arr[3]),
      album: dco_decode_opt_String(arr[4]),
      durationMs: dco_decode_opt_box_autoadd_i_64(arr[5]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Library sse_decode_RustOpaque_Library(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return LibraryImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  Player sse_decode_RustOpaque_Player(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<Event> sse_decode_StreamSink_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<LibraryEvent> sse_decode_StreamSink_library_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  Event sse_decode_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_state = sse_decode_player_state(deserializer);
        return Event_StateChanged(state: var_state);
      case 1:
        var var_ms = sse_decode_i_64(deserializer);
        return Event_Position(ms: var_ms);
      case 2:
        var var_path = sse_decode_String(deserializer);
        return Event_TrackChanged(path: var_path);
      case 3:
        var var_path = sse_decode_String(deserializer);
        return Event_PlaybackEnded(path: var_path);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return Event_Error(message: var_message);
      case 5:
        var var_message = sse_decode_String(deserializer);
        return Event_Log(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LibraryEvent sse_decode_library_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_paths = sse_decode_list_String(deserializer);
        return LibraryEvent_Roots(paths: var_paths);
      case 1:
        var var_paths = sse_decode_list_String(deserializer);
        return LibraryEvent_Folders(paths: var_paths);
      case 2:
        var var_paths = sse_decode_list_String(deserializer);
        return LibraryEvent_ExcludedFolders(paths: var_paths);
      case 3:
        return LibraryEvent_Changed();
      case 4:
        var var_folder = sse_decode_String(deserializer);
        var var_recursive = sse_decode_bool(deserializer);
        var var_query = sse_decode_String(deserializer);
        var var_items = sse_decode_list_track_lite(deserializer);
        return LibraryEvent_Tracks(
          folder: var_folder,
          recursive: var_recursive,
          query: var_query,
          items: var_items,
        );
      case 5:
        var var_scanned = sse_decode_i_64(deserializer);
        var var_updated = sse_decode_i_64(deserializer);
        var var_skipped = sse_decode_i_64(deserializer);
        var var_errors = sse_decode_i_64(deserializer);
        return LibraryEvent_ScanProgress(
          scanned: var_scanned,
          updated: var_updated,
          skipped: var_skipped,
          errors: var_errors,
        );
      case 6:
        var var_durationMs = sse_decode_i_64(deserializer);
        var var_scanned = sse_decode_i_64(deserializer);
        var var_updated = sse_decode_i_64(deserializer);
        var var_skipped = sse_decode_i_64(deserializer);
        var var_errors = sse_decode_i_64(deserializer);
        return LibraryEvent_ScanFinished(
          durationMs: var_durationMs,
          scanned: var_scanned,
          updated: var_updated,
          skipped: var_skipped,
          errors: var_errors,
        );
      case 7:
        var var_query = sse_decode_String(deserializer);
        var var_items = sse_decode_list_track_lite(deserializer);
        return LibraryEvent_SearchResult(query: var_query, items: var_items);
      case 8:
        var var_message = sse_decode_String(deserializer);
        return LibraryEvent_Error(message: var_message);
      case 9:
        var var_message = sse_decode_String(deserializer);
        return LibraryEvent_Log(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TrackLite> sse_decode_list_track_lite(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TrackLite>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_track_lite(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlayerState.values[inner];
  }

  @protected
  TrackLite sse_decode_track_lite(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_artist = sse_decode_opt_String(deserializer);
    var var_album = sse_decode_opt_String(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    return TrackLite(
      id: var_id,
      path: var_path,
      title: var_title,
      artist: var_artist,
      album: var_album,
      durationMs: var_durationMs,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_RustOpaque_Library(Library self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as LibraryImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_RustOpaque_Player(Player self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PlayerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_event_Sse(
    RustStreamSink<Event> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_library_event_Sse(
    RustStreamSink<LibraryEvent> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_library_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_event(Event self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Event_StateChanged(state: final state):
        sse_encode_i_32(0, serializer);
        sse_encode_player_state(state, serializer);
      case Event_Position(ms: final ms):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(ms, serializer);
      case Event_TrackChanged(path: final path):
        sse_encode_i_32(2, serializer);
        sse_encode_String(path, serializer);
      case Event_PlaybackEnded(path: final path):
        sse_encode_i_32(3, serializer);
        sse_encode_String(path, serializer);
      case Event_Error(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
      case Event_Log(message: final message):
        sse_encode_i_32(5, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_library_event(LibraryEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case LibraryEvent_Roots(paths: final paths):
        sse_encode_i_32(0, serializer);
        sse_encode_list_String(paths, serializer);
      case LibraryEvent_Folders(paths: final paths):
        sse_encode_i_32(1, serializer);
        sse_encode_list_String(paths, serializer);
      case LibraryEvent_ExcludedFolders(paths: final paths):
        sse_encode_i_32(2, serializer);
        sse_encode_list_String(paths, serializer);
      case LibraryEvent_Changed():
        sse_encode_i_32(3, serializer);
      case LibraryEvent_Tracks(
        folder: final folder,
        recursive: final recursive,
        query: final query,
        items: final items,
      ):
        sse_encode_i_32(4, serializer);
        sse_encode_String(folder, serializer);
        sse_encode_bool(recursive, serializer);
        sse_encode_String(query, serializer);
        sse_encode_list_track_lite(items, serializer);
      case LibraryEvent_ScanProgress(
        scanned: final scanned,
        updated: final updated,
        skipped: final skipped,
        errors: final errors,
      ):
        sse_encode_i_32(5, serializer);
        sse_encode_i_64(scanned, serializer);
        sse_encode_i_64(updated, serializer);
        sse_encode_i_64(skipped, serializer);
        sse_encode_i_64(errors, serializer);
      case LibraryEvent_ScanFinished(
        durationMs: final durationMs,
        scanned: final scanned,
        updated: final updated,
        skipped: final skipped,
        errors: final errors,
      ):
        sse_encode_i_32(6, serializer);
        sse_encode_i_64(durationMs, serializer);
        sse_encode_i_64(scanned, serializer);
        sse_encode_i_64(updated, serializer);
        sse_encode_i_64(skipped, serializer);
        sse_encode_i_64(errors, serializer);
      case LibraryEvent_SearchResult(query: final query, items: final items):
        sse_encode_i_32(7, serializer);
        sse_encode_String(query, serializer);
        sse_encode_list_track_lite(items, serializer);
      case LibraryEvent_Error(message: final message):
        sse_encode_i_32(8, serializer);
        sse_encode_String(message, serializer);
      case LibraryEvent_Log(message: final message):
        sse_encode_i_32(9, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_track_lite(
    List<TrackLite> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_track_lite(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_track_lite(TrackLite self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.artist, serializer);
    sse_encode_opt_String(self.album, serializer);
    sse_encode_opt_box_autoadd_i_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class LibraryImpl extends RustOpaque implements Library {
  // Not to be used by end users
  LibraryImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  LibraryImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        StellatuneApi.instance.api.rust_arc_increment_strong_count_Library,
    rustArcDecrementStrongCount:
        StellatuneApi.instance.api.rust_arc_decrement_strong_count_Library,
    rustArcDecrementStrongCountPtr:
        StellatuneApi.instance.api.rust_arc_decrement_strong_count_LibraryPtr,
  );
}

@sealed
class PlayerImpl extends RustOpaque implements Player {
  // Not to be used by end users
  PlayerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PlayerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        StellatuneApi.instance.api.rust_arc_increment_strong_count_Player,
    rustArcDecrementStrongCount:
        StellatuneApi.instance.api.rust_arc_decrement_strong_count_Player,
    rustArcDecrementStrongCountPtr:
        StellatuneApi.instance.api.rust_arc_decrement_strong_count_PlayerPtr,
  );
}
