// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/dlna.dart';
import 'api/library.dart';
import 'api/player.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'third_party/stellatune_core.dart';

abstract class StellatuneApiApiImplPlatform
    extends BaseApiImpl<StellatuneApiWire> {
  StellatuneApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LibraryPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_Library;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PlayerPtr =>
      wire.rust_arc_decrement_strong_count_RustOpaque_Player;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_RequestIdPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RequestId
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    dynamic raw,
  );

  @protected
  RequestId
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    dynamic raw,
  );

  @protected
  Library dco_decode_RustOpaque_Library(dynamic raw);

  @protected
  Player dco_decode_RustOpaque_Player(dynamic raw);

  @protected
  RequestId
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    dynamic raw,
  );

  @protected
  RustStreamSink<Event> dco_decode_StreamSink_event_Sse(dynamic raw);

  @protected
  RustStreamSink<LibraryEvent> dco_decode_StreamSink_library_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<LyricsEvent> dco_decode_StreamSink_lyrics_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PluginRuntimeEvent>
  dco_decode_StreamSink_plugin_runtime_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AudioBackend dco_decode_audio_backend(dynamic raw);

  @protected
  AudioDevice dco_decode_audio_device(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DlnaRenderer dco_decode_box_autoadd_dlna_renderer(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LyricsDoc dco_decode_box_autoadd_lyrics_doc(dynamic raw);

  @protected
  LyricsQuery dco_decode_box_autoadd_lyrics_query(dynamic raw);

  @protected
  OutputSinkRoute dco_decode_box_autoadd_output_sink_route(dynamic raw);

  @protected
  TrackDecodeInfo dco_decode_box_autoadd_track_decode_info(dynamic raw);

  @protected
  TrackRef dco_decode_box_autoadd_track_ref(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DlnaHttpServerInfo dco_decode_dlna_http_server_info(dynamic raw);

  @protected
  DlnaPositionInfo dco_decode_dlna_position_info(dynamic raw);

  @protected
  DlnaRenderer dco_decode_dlna_renderer(dynamic raw);

  @protected
  DlnaSsdpDevice dco_decode_dlna_ssdp_device(dynamic raw);

  @protected
  DlnaTransportInfo dco_decode_dlna_transport_info(dynamic raw);

  @protected
  DspChainItem dco_decode_dsp_chain_item(dynamic raw);

  @protected
  DspTypeDescriptor dco_decode_dsp_type_descriptor(dynamic raw);

  @protected
  Event dco_decode_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LfeMode dco_decode_lfe_mode(dynamic raw);

  @protected
  LibraryEvent dco_decode_library_event(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AudioDevice> dco_decode_list_audio_device(dynamic raw);

  @protected
  List<DlnaRenderer> dco_decode_list_dlna_renderer(dynamic raw);

  @protected
  List<DlnaSsdpDevice> dco_decode_list_dlna_ssdp_device(dynamic raw);

  @protected
  List<DspChainItem> dco_decode_list_dsp_chain_item(dynamic raw);

  @protected
  List<DspTypeDescriptor> dco_decode_list_dsp_type_descriptor(dynamic raw);

  @protected
  List<LyricLine> dco_decode_list_lyric_line(dynamic raw);

  @protected
  List<LyricsProviderTypeDescriptor>
  dco_decode_list_lyrics_provider_type_descriptor(dynamic raw);

  @protected
  List<LyricsSearchCandidate> dco_decode_list_lyrics_search_candidate(
    dynamic raw,
  );

  @protected
  List<OutputSinkTypeDescriptor> dco_decode_list_output_sink_type_descriptor(
    dynamic raw,
  );

  @protected
  List<PlaylistLite> dco_decode_list_playlist_lite(dynamic raw);

  @protected
  List<PluginDescriptor> dco_decode_list_plugin_descriptor(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SourceCatalogTypeDescriptor>
  dco_decode_list_source_catalog_type_descriptor(dynamic raw);

  @protected
  List<TrackLite> dco_decode_list_track_lite(dynamic raw);

  @protected
  LyricLine dco_decode_lyric_line(dynamic raw);

  @protected
  LyricsDoc dco_decode_lyrics_doc(dynamic raw);

  @protected
  LyricsEvent dco_decode_lyrics_event(dynamic raw);

  @protected
  LyricsProviderTypeDescriptor dco_decode_lyrics_provider_type_descriptor(
    dynamic raw,
  );

  @protected
  LyricsQuery dco_decode_lyrics_query(dynamic raw);

  @protected
  LyricsSearchCandidate dco_decode_lyrics_search_candidate(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  TrackDecodeInfo? dco_decode_opt_box_autoadd_track_decode_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  OutputSinkRoute dco_decode_output_sink_route(dynamic raw);

  @protected
  OutputSinkTypeDescriptor dco_decode_output_sink_type_descriptor(dynamic raw);

  @protected
  PlayerState dco_decode_player_state(dynamic raw);

  @protected
  PlaylistLite dco_decode_playlist_lite(dynamic raw);

  @protected
  PluginDescriptor dco_decode_plugin_descriptor(dynamic raw);

  @protected
  PluginRuntimeEvent dco_decode_plugin_runtime_event(dynamic raw);

  @protected
  PluginRuntimeKind dco_decode_plugin_runtime_kind(dynamic raw);

  @protected
  SourceCatalogTypeDescriptor dco_decode_source_catalog_type_descriptor(
    dynamic raw,
  );

  @protected
  TrackDecodeInfo dco_decode_track_decode_info(dynamic raw);

  @protected
  TrackLite dco_decode_track_lite(dynamic raw);

  @protected
  TrackRef dco_decode_track_ref(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RequestId
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    SseDeserializer deserializer,
  );

  @protected
  RequestId
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    SseDeserializer deserializer,
  );

  @protected
  Library sse_decode_RustOpaque_Library(SseDeserializer deserializer);

  @protected
  Player sse_decode_RustOpaque_Player(SseDeserializer deserializer);

  @protected
  RequestId
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Event> sse_decode_StreamSink_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LibraryEvent> sse_decode_StreamSink_library_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LyricsEvent> sse_decode_StreamSink_lyrics_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PluginRuntimeEvent>
  sse_decode_StreamSink_plugin_runtime_event_Sse(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AudioBackend sse_decode_audio_backend(SseDeserializer deserializer);

  @protected
  AudioDevice sse_decode_audio_device(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DlnaRenderer sse_decode_box_autoadd_dlna_renderer(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LyricsDoc sse_decode_box_autoadd_lyrics_doc(SseDeserializer deserializer);

  @protected
  LyricsQuery sse_decode_box_autoadd_lyrics_query(SseDeserializer deserializer);

  @protected
  OutputSinkRoute sse_decode_box_autoadd_output_sink_route(
    SseDeserializer deserializer,
  );

  @protected
  TrackDecodeInfo sse_decode_box_autoadd_track_decode_info(
    SseDeserializer deserializer,
  );

  @protected
  TrackRef sse_decode_box_autoadd_track_ref(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DlnaHttpServerInfo sse_decode_dlna_http_server_info(
    SseDeserializer deserializer,
  );

  @protected
  DlnaPositionInfo sse_decode_dlna_position_info(SseDeserializer deserializer);

  @protected
  DlnaRenderer sse_decode_dlna_renderer(SseDeserializer deserializer);

  @protected
  DlnaSsdpDevice sse_decode_dlna_ssdp_device(SseDeserializer deserializer);

  @protected
  DlnaTransportInfo sse_decode_dlna_transport_info(
    SseDeserializer deserializer,
  );

  @protected
  DspChainItem sse_decode_dsp_chain_item(SseDeserializer deserializer);

  @protected
  DspTypeDescriptor sse_decode_dsp_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  Event sse_decode_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LfeMode sse_decode_lfe_mode(SseDeserializer deserializer);

  @protected
  LibraryEvent sse_decode_library_event(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AudioDevice> sse_decode_list_audio_device(SseDeserializer deserializer);

  @protected
  List<DlnaRenderer> sse_decode_list_dlna_renderer(
    SseDeserializer deserializer,
  );

  @protected
  List<DlnaSsdpDevice> sse_decode_list_dlna_ssdp_device(
    SseDeserializer deserializer,
  );

  @protected
  List<DspChainItem> sse_decode_list_dsp_chain_item(
    SseDeserializer deserializer,
  );

  @protected
  List<DspTypeDescriptor> sse_decode_list_dsp_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<LyricLine> sse_decode_list_lyric_line(SseDeserializer deserializer);

  @protected
  List<LyricsProviderTypeDescriptor>
  sse_decode_list_lyrics_provider_type_descriptor(SseDeserializer deserializer);

  @protected
  List<LyricsSearchCandidate> sse_decode_list_lyrics_search_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<OutputSinkTypeDescriptor> sse_decode_list_output_sink_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaylistLite> sse_decode_list_playlist_lite(
    SseDeserializer deserializer,
  );

  @protected
  List<PluginDescriptor> sse_decode_list_plugin_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SourceCatalogTypeDescriptor>
  sse_decode_list_source_catalog_type_descriptor(SseDeserializer deserializer);

  @protected
  List<TrackLite> sse_decode_list_track_lite(SseDeserializer deserializer);

  @protected
  LyricLine sse_decode_lyric_line(SseDeserializer deserializer);

  @protected
  LyricsDoc sse_decode_lyrics_doc(SseDeserializer deserializer);

  @protected
  LyricsEvent sse_decode_lyrics_event(SseDeserializer deserializer);

  @protected
  LyricsProviderTypeDescriptor sse_decode_lyrics_provider_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  LyricsQuery sse_decode_lyrics_query(SseDeserializer deserializer);

  @protected
  LyricsSearchCandidate sse_decode_lyrics_search_candidate(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  TrackDecodeInfo? sse_decode_opt_box_autoadd_track_decode_info(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  OutputSinkRoute sse_decode_output_sink_route(SseDeserializer deserializer);

  @protected
  OutputSinkTypeDescriptor sse_decode_output_sink_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer);

  @protected
  PlaylistLite sse_decode_playlist_lite(SseDeserializer deserializer);

  @protected
  PluginDescriptor sse_decode_plugin_descriptor(SseDeserializer deserializer);

  @protected
  PluginRuntimeEvent sse_decode_plugin_runtime_event(
    SseDeserializer deserializer,
  );

  @protected
  PluginRuntimeKind sse_decode_plugin_runtime_kind(
    SseDeserializer deserializer,
  );

  @protected
  SourceCatalogTypeDescriptor sse_decode_source_catalog_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  TrackDecodeInfo sse_decode_track_decode_info(SseDeserializer deserializer);

  @protected
  TrackLite sse_decode_track_lite(SseDeserializer deserializer);

  @protected
  TrackRef sse_decode_track_ref(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    RequestId self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    RequestId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_Library(Library self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_Player(Player self, SseSerializer serializer);

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    RequestId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_event_Sse(
    RustStreamSink<Event> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_library_event_Sse(
    RustStreamSink<LibraryEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_lyrics_event_Sse(
    RustStreamSink<LyricsEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_plugin_runtime_event_Sse(
    RustStreamSink<PluginRuntimeEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_audio_backend(AudioBackend self, SseSerializer serializer);

  @protected
  void sse_encode_audio_device(AudioDevice self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dlna_renderer(
    DlnaRenderer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lyrics_doc(
    LyricsDoc self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lyrics_query(
    LyricsQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_output_sink_route(
    OutputSinkRoute self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_decode_info(
    TrackDecodeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_ref(
    TrackRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_dlna_http_server_info(
    DlnaHttpServerInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_position_info(
    DlnaPositionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_renderer(DlnaRenderer self, SseSerializer serializer);

  @protected
  void sse_encode_dlna_ssdp_device(
    DlnaSsdpDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_transport_info(
    DlnaTransportInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dsp_chain_item(DspChainItem self, SseSerializer serializer);

  @protected
  void sse_encode_dsp_type_descriptor(
    DspTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_event(Event self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_lfe_mode(LfeMode self, SseSerializer serializer);

  @protected
  void sse_encode_library_event(LibraryEvent self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_device(
    List<AudioDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dlna_renderer(
    List<DlnaRenderer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dlna_ssdp_device(
    List<DlnaSsdpDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dsp_chain_item(
    List<DspChainItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dsp_type_descriptor(
    List<DspTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lyric_line(
    List<LyricLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lyrics_provider_type_descriptor(
    List<LyricsProviderTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lyrics_search_candidate(
    List<LyricsSearchCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_output_sink_type_descriptor(
    List<OutputSinkTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist_lite(
    List<PlaylistLite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_plugin_descriptor(
    List<PluginDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_catalog_type_descriptor(
    List<SourceCatalogTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track_lite(
    List<TrackLite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lyric_line(LyricLine self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_doc(LyricsDoc self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_event(LyricsEvent self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_provider_type_descriptor(
    LyricsProviderTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lyrics_query(LyricsQuery self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_search_candidate(
    LyricsSearchCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_track_decode_info(
    TrackDecodeInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_output_sink_route(
    OutputSinkRoute self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_sink_type_descriptor(
    OutputSinkTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_lite(PlaylistLite self, SseSerializer serializer);

  @protected
  void sse_encode_plugin_descriptor(
    PluginDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_plugin_runtime_event(
    PluginRuntimeEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_plugin_runtime_kind(
    PluginRuntimeKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_catalog_type_descriptor(
    SourceCatalogTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_decode_info(
    TrackDecodeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_lite(TrackLite self, SseSerializer serializer);

  @protected
  void sse_encode_track_ref(TrackRef self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class StellatuneApiWire implements BaseWire {
  StellatuneApiWire.fromExternalLibrary(ExternalLibrary lib);

  void rust_arc_increment_strong_count_RustOpaque_Library(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_Library(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_Library(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_Library(ptr);

  void rust_arc_increment_strong_count_RustOpaque_Player(int ptr) =>
      wasmModule.rust_arc_increment_strong_count_RustOpaque_Player(ptr);

  void rust_arc_decrement_strong_count_RustOpaque_Player(int ptr) =>
      wasmModule.rust_arc_decrement_strong_count_RustOpaque_Player(ptr);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
        ptr,
      );
}

@JS('wasm_bindgen')
external StellatuneApiWasmModule get wasmModule;

@JS()
@anonymous
extension type StellatuneApiWasmModule._(JSObject _) implements JSObject {
  external void rust_arc_increment_strong_count_RustOpaque_Library(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_Library(int ptr);

  external void rust_arc_increment_strong_count_RustOpaque_Player(int ptr);

  external void rust_arc_decrement_strong_count_RustOpaque_Player(int ptr);

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRequestId(
    int ptr,
  );
}
