// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/diagnostics.dart';
import 'api/dlna.dart';
import 'api/dlna/types.dart';
import 'api/error.dart';
import 'api/events.dart';
import 'api/library.dart';
import 'api/media_catalog.dart';
import 'api/player.dart';
import 'api/player/queue.dart';
import 'api/player/transcode.dart';
import 'api/player/types.dart';
import 'api/runtime.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

import 'third_party/stellatune_backend_api/diagnostics/model.dart';
import 'third_party/stellatune_backend_api/lyrics_types.dart';
import 'third_party/stellatune_backend_api/player_service/catalog.dart';
import 'third_party/stellatune_backend_api/player_service/error.dart';
import 'third_party/stellatune_backend_api/player_service/identity.dart';
import 'third_party/stellatune_backend_api/player_service/metadata.dart';
import 'third_party/stellatune_backend_api/player_service/service.dart';
import 'third_party/stellatune_library.dart';
import 'third_party/stellatune_library/catalog.dart';

abstract class StellatuneApiApiImplPlatform
    extends BaseApiImpl<StellatuneApiWire> {
  StellatuneApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_LocalCatalogPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalogPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PlayerCatalogPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalogPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PlayerServicePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServicePtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_PlayerServiceErrorPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceErrorPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_TrackIdPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackIdPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  LocalCatalog
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    dynamic raw,
  );

  @protected
  PlayerCatalog
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    dynamic raw,
  );

  @protected
  PlayerService
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    dynamic raw,
  );

  @protected
  PlayerServiceError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
    dynamic raw,
  );

  @protected
  TrackId
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    dynamic raw,
  );

  @protected
  LocalCatalog
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    dynamic raw,
  );

  @protected
  PlayerCatalog
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    dynamic raw,
  );

  @protected
  PlayerService
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    dynamic raw,
  );

  @protected
  Map<TrackId, ProviderQueueMetadata>
  dco_decode_Map_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId_provider_queue_metadata_None(
    dynamic raw,
  );

  @protected
  LocalCatalog
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    dynamic raw,
  );

  @protected
  PlayerCatalog
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    dynamic raw,
  );

  @protected
  PlayerService
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    dynamic raw,
  );

  @protected
  PlayerServiceError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
    dynamic raw,
  );

  @protected
  TrackId
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    dynamic raw,
  );

  @protected
  RustStreamSink<Event> dco_decode_StreamSink_event_Sse(dynamic raw);

  @protected
  RustStreamSink<LibraryEvent> dco_decode_StreamSink_library_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogBatch> dco_decode_StreamSink_log_batch_Sse(dynamic raw);

  @protected
  RustStreamSink<LyricsEvent> dco_decode_StreamSink_lyrics_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PlaybackQueue> dco_decode_StreamSink_playback_queue_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TranscodeProgressEvent>
  dco_decode_StreamSink_transcode_progress_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AppError dco_decode_app_error(dynamic raw);

  @protected
  AudioBackend dco_decode_audio_backend(dynamic raw);

  @protected
  AudioDevice dco_decode_audio_device(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AppError dco_decode_box_autoadd_app_error(dynamic raw);

  @protected
  CatalogQuery dco_decode_box_autoadd_catalog_query(dynamic raw);

  @protected
  DlnaRenderer dco_decode_box_autoadd_dlna_renderer(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  LogRecord dco_decode_box_autoadd_log_record(dynamic raw);

  @protected
  LyricsDoc dco_decode_box_autoadd_lyrics_doc(dynamic raw);

  @protected
  LyricsQuery dco_decode_box_autoadd_lyrics_query(dynamic raw);

  @protected
  MediaRef dco_decode_box_autoadd_media_ref(dynamic raw);

  @protected
  OutputSinkRoute dco_decode_box_autoadd_output_sink_route(dynamic raw);

  @protected
  QueueProviderTrack dco_decode_box_autoadd_queue_provider_track(dynamic raw);

  @protected
  TrackCover dco_decode_box_autoadd_track_cover(dynamic raw);

  @protected
  TrackDecodeInfo dco_decode_box_autoadd_track_decode_info(dynamic raw);

  @protected
  TrackLite dco_decode_box_autoadd_track_lite(dynamic raw);

  @protected
  TrackPresentation dco_decode_box_autoadd_track_presentation(dynamic raw);

  @protected
  TranscodeTrackLocalRequest
  dco_decode_box_autoadd_transcode_track_local_request(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  CatalogItem dco_decode_catalog_item(dynamic raw);

  @protected
  CatalogPage dco_decode_catalog_page(dynamic raw);

  @protected
  CatalogQuery dco_decode_catalog_query(dynamic raw);

  @protected
  CatalogSort dco_decode_catalog_sort(dynamic raw);

  @protected
  DlnaHttpServerInfo dco_decode_dlna_http_server_info(dynamic raw);

  @protected
  DlnaPositionInfo dco_decode_dlna_position_info(dynamic raw);

  @protected
  DlnaRenderer dco_decode_dlna_renderer(dynamic raw);

  @protected
  DlnaSsdpDevice dco_decode_dlna_ssdp_device(dynamic raw);

  @protected
  DlnaTransportInfo dco_decode_dlna_transport_info(dynamic raw);

  @protected
  DspChainItem dco_decode_dsp_chain_item(dynamic raw);

  @protected
  DspTypeDescriptor dco_decode_dsp_type_descriptor(dynamic raw);

  @protected
  EncoderTypeDescriptor dco_decode_encoder_type_descriptor(dynamic raw);

  @protected
  ErrorCategory dco_decode_error_category(dynamic raw);

  @protected
  Event dco_decode_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LfeMode dco_decode_lfe_mode(dynamic raw);

  @protected
  LibraryEvent dco_decode_library_event(dynamic raw);

  @protected
  LibrarySource dco_decode_library_source(dynamic raw);

  @protected
  List<TrackId>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AudioDevice> dco_decode_list_audio_device(dynamic raw);

  @protected
  List<CatalogItem> dco_decode_list_catalog_item(dynamic raw);

  @protected
  List<CatalogSort> dco_decode_list_catalog_sort(dynamic raw);

  @protected
  List<DlnaRenderer> dco_decode_list_dlna_renderer(dynamic raw);

  @protected
  List<DlnaSsdpDevice> dco_decode_list_dlna_ssdp_device(dynamic raw);

  @protected
  List<DspChainItem> dco_decode_list_dsp_chain_item(dynamic raw);

  @protected
  List<DspTypeDescriptor> dco_decode_list_dsp_type_descriptor(dynamic raw);

  @protected
  List<EncoderTypeDescriptor> dco_decode_list_encoder_type_descriptor(
    dynamic raw,
  );

  @protected
  List<LibrarySource> dco_decode_list_library_source(dynamic raw);

  @protected
  List<LogRecord> dco_decode_list_log_record(dynamic raw);

  @protected
  List<LyricLine> dco_decode_list_lyric_line(dynamic raw);

  @protected
  List<LyricsProviderTypeDescriptor>
  dco_decode_list_lyrics_provider_type_descriptor(dynamic raw);

  @protected
  List<LyricsSearchCandidate> dco_decode_list_lyrics_search_candidate(
    dynamic raw,
  );

  @protected
  List<MediaKind> dco_decode_list_media_kind(dynamic raw);

  @protected
  List<MediaRef> dco_decode_list_media_ref(dynamic raw);

  @protected
  List<OutputSinkTypeDescriptor> dco_decode_list_output_sink_type_descriptor(
    dynamic raw,
  );

  @protected
  List<PlaylistLite> dco_decode_list_playlist_lite(dynamic raw);

  @protected
  List<PluginDescriptor> dco_decode_list_plugin_descriptor(dynamic raw);

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<QueueEntry> dco_decode_list_queue_entry(dynamic raw);

  @protected
  List<QueueMetadataUpdate> dco_decode_list_queue_metadata_update(dynamic raw);

  @protected
  List<(TrackId, ProviderQueueMetadata)>
  dco_decode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_provider_queue_metadata(
    dynamic raw,
  );

  @protected
  List<(TrackId, TrackPresentation)>
  dco_decode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_track_presentation(
    dynamic raw,
  );

  @protected
  List<SourceCatalogTypeDescriptor>
  dco_decode_list_source_catalog_type_descriptor(dynamic raw);

  @protected
  List<TrackLite> dco_decode_list_track_lite(dynamic raw);

  @protected
  LogBatch dco_decode_log_batch(dynamic raw);

  @protected
  LogPage dco_decode_log_page(dynamic raw);

  @protected
  LogRecord dco_decode_log_record(dynamic raw);

  @protected
  LyricLine dco_decode_lyric_line(dynamic raw);

  @protected
  LyricsDoc dco_decode_lyrics_doc(dynamic raw);

  @protected
  LyricsEvent dco_decode_lyrics_event(dynamic raw);

  @protected
  LyricsProviderTypeDescriptor dco_decode_lyrics_provider_type_descriptor(
    dynamic raw,
  );

  @protected
  LyricsQuery dco_decode_lyrics_query(dynamic raw);

  @protected
  LyricsSearchCandidate dco_decode_lyrics_search_candidate(dynamic raw);

  @protected
  MediaKind dco_decode_media_kind(dynamic raw);

  @protected
  MediaRef dco_decode_media_ref(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AppError? dco_decode_opt_box_autoadd_app_error(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  MediaRef? dco_decode_opt_box_autoadd_media_ref(dynamic raw);

  @protected
  QueueProviderTrack? dco_decode_opt_box_autoadd_queue_provider_track(
    dynamic raw,
  );

  @protected
  TrackCover? dco_decode_opt_box_autoadd_track_cover(dynamic raw);

  @protected
  TrackDecodeInfo? dco_decode_opt_box_autoadd_track_decode_info(dynamic raw);

  @protected
  TrackLite? dco_decode_opt_box_autoadd_track_lite(dynamic raw);

  @protected
  TrackPresentation? dco_decode_opt_box_autoadd_track_presentation(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  OutputSinkRoute dco_decode_output_sink_route(dynamic raw);

  @protected
  OutputSinkTypeDescriptor dco_decode_output_sink_type_descriptor(dynamic raw);

  @protected
  PlaybackLatency dco_decode_playback_latency(dynamic raw);

  @protected
  PlaybackQueue dco_decode_playback_queue(dynamic raw);

  @protected
  PlaybackSnapshot dco_decode_playback_snapshot(dynamic raw);

  @protected
  PlayerState dco_decode_player_state(dynamic raw);

  @protected
  PlaylistLite dco_decode_playlist_lite(dynamic raw);

  @protected
  PluginDescriptor dco_decode_plugin_descriptor(dynamic raw);

  @protected
  ProviderQueueMetadata dco_decode_provider_queue_metadata(dynamic raw);

  @protected
  QueueEntry dco_decode_queue_entry(dynamic raw);

  @protected
  QueueMetadataUpdate dco_decode_queue_metadata_update(dynamic raw);

  @protected
  QueueProviderTrack dco_decode_queue_provider_track(dynamic raw);

  @protected
  QueueRepeatMode dco_decode_queue_repeat_mode(dynamic raw);

  @protected
  (TrackId, ProviderQueueMetadata)
  dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_provider_queue_metadata(
    dynamic raw,
  );

  @protected
  (TrackId, TrackPresentation)
  dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_track_presentation(
    dynamic raw,
  );

  @protected
  ResampleQuality dco_decode_resample_quality(dynamic raw);

  @protected
  SourceCatalogTypeDescriptor dco_decode_source_catalog_type_descriptor(
    dynamic raw,
  );

  @protected
  TrackCover dco_decode_track_cover(dynamic raw);

  @protected
  TrackCoverKind dco_decode_track_cover_kind(dynamic raw);

  @protected
  TrackDecodeInfo dco_decode_track_decode_info(dynamic raw);

  @protected
  TrackLite dco_decode_track_lite(dynamic raw);

  @protected
  TrackPresentation dco_decode_track_presentation(dynamic raw);

  @protected
  TranscodeProgressEvent dco_decode_transcode_progress_event(dynamic raw);

  @protected
  TranscodeTrackLocalRequest dco_decode_transcode_track_local_request(
    dynamic raw,
  );

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  LocalCatalog
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    SseDeserializer deserializer,
  );

  @protected
  PlayerCatalog
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    SseDeserializer deserializer,
  );

  @protected
  PlayerService
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    SseDeserializer deserializer,
  );

  @protected
  PlayerServiceError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
    SseDeserializer deserializer,
  );

  @protected
  TrackId
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    SseDeserializer deserializer,
  );

  @protected
  LocalCatalog
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    SseDeserializer deserializer,
  );

  @protected
  PlayerCatalog
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    SseDeserializer deserializer,
  );

  @protected
  PlayerService
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    SseDeserializer deserializer,
  );

  @protected
  Map<TrackId, ProviderQueueMetadata>
  sse_decode_Map_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId_provider_queue_metadata_None(
    SseDeserializer deserializer,
  );

  @protected
  LocalCatalog
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    SseDeserializer deserializer,
  );

  @protected
  PlayerCatalog
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    SseDeserializer deserializer,
  );

  @protected
  PlayerService
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    SseDeserializer deserializer,
  );

  @protected
  PlayerServiceError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
    SseDeserializer deserializer,
  );

  @protected
  TrackId
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<Event> sse_decode_StreamSink_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LibraryEvent> sse_decode_StreamSink_library_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogBatch> sse_decode_StreamSink_log_batch_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LyricsEvent> sse_decode_StreamSink_lyrics_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PlaybackQueue> sse_decode_StreamSink_playback_queue_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TranscodeProgressEvent>
  sse_decode_StreamSink_transcode_progress_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AppError sse_decode_app_error(SseDeserializer deserializer);

  @protected
  AudioBackend sse_decode_audio_backend(SseDeserializer deserializer);

  @protected
  AudioDevice sse_decode_audio_device(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AppError sse_decode_box_autoadd_app_error(SseDeserializer deserializer);

  @protected
  CatalogQuery sse_decode_box_autoadd_catalog_query(
    SseDeserializer deserializer,
  );

  @protected
  DlnaRenderer sse_decode_box_autoadd_dlna_renderer(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  LogRecord sse_decode_box_autoadd_log_record(SseDeserializer deserializer);

  @protected
  LyricsDoc sse_decode_box_autoadd_lyrics_doc(SseDeserializer deserializer);

  @protected
  LyricsQuery sse_decode_box_autoadd_lyrics_query(SseDeserializer deserializer);

  @protected
  MediaRef sse_decode_box_autoadd_media_ref(SseDeserializer deserializer);

  @protected
  OutputSinkRoute sse_decode_box_autoadd_output_sink_route(
    SseDeserializer deserializer,
  );

  @protected
  QueueProviderTrack sse_decode_box_autoadd_queue_provider_track(
    SseDeserializer deserializer,
  );

  @protected
  TrackCover sse_decode_box_autoadd_track_cover(SseDeserializer deserializer);

  @protected
  TrackDecodeInfo sse_decode_box_autoadd_track_decode_info(
    SseDeserializer deserializer,
  );

  @protected
  TrackLite sse_decode_box_autoadd_track_lite(SseDeserializer deserializer);

  @protected
  TrackPresentation sse_decode_box_autoadd_track_presentation(
    SseDeserializer deserializer,
  );

  @protected
  TranscodeTrackLocalRequest
  sse_decode_box_autoadd_transcode_track_local_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  CatalogItem sse_decode_catalog_item(SseDeserializer deserializer);

  @protected
  CatalogPage sse_decode_catalog_page(SseDeserializer deserializer);

  @protected
  CatalogQuery sse_decode_catalog_query(SseDeserializer deserializer);

  @protected
  CatalogSort sse_decode_catalog_sort(SseDeserializer deserializer);

  @protected
  DlnaHttpServerInfo sse_decode_dlna_http_server_info(
    SseDeserializer deserializer,
  );

  @protected
  DlnaPositionInfo sse_decode_dlna_position_info(SseDeserializer deserializer);

  @protected
  DlnaRenderer sse_decode_dlna_renderer(SseDeserializer deserializer);

  @protected
  DlnaSsdpDevice sse_decode_dlna_ssdp_device(SseDeserializer deserializer);

  @protected
  DlnaTransportInfo sse_decode_dlna_transport_info(
    SseDeserializer deserializer,
  );

  @protected
  DspChainItem sse_decode_dsp_chain_item(SseDeserializer deserializer);

  @protected
  DspTypeDescriptor sse_decode_dsp_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  EncoderTypeDescriptor sse_decode_encoder_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  ErrorCategory sse_decode_error_category(SseDeserializer deserializer);

  @protected
  Event sse_decode_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LfeMode sse_decode_lfe_mode(SseDeserializer deserializer);

  @protected
  LibraryEvent sse_decode_library_event(SseDeserializer deserializer);

  @protected
  LibrarySource sse_decode_library_source(SseDeserializer deserializer);

  @protected
  List<TrackId>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AudioDevice> sse_decode_list_audio_device(SseDeserializer deserializer);

  @protected
  List<CatalogItem> sse_decode_list_catalog_item(SseDeserializer deserializer);

  @protected
  List<CatalogSort> sse_decode_list_catalog_sort(SseDeserializer deserializer);

  @protected
  List<DlnaRenderer> sse_decode_list_dlna_renderer(
    SseDeserializer deserializer,
  );

  @protected
  List<DlnaSsdpDevice> sse_decode_list_dlna_ssdp_device(
    SseDeserializer deserializer,
  );

  @protected
  List<DspChainItem> sse_decode_list_dsp_chain_item(
    SseDeserializer deserializer,
  );

  @protected
  List<DspTypeDescriptor> sse_decode_list_dsp_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<EncoderTypeDescriptor> sse_decode_list_encoder_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<LibrarySource> sse_decode_list_library_source(
    SseDeserializer deserializer,
  );

  @protected
  List<LogRecord> sse_decode_list_log_record(SseDeserializer deserializer);

  @protected
  List<LyricLine> sse_decode_list_lyric_line(SseDeserializer deserializer);

  @protected
  List<LyricsProviderTypeDescriptor>
  sse_decode_list_lyrics_provider_type_descriptor(SseDeserializer deserializer);

  @protected
  List<LyricsSearchCandidate> sse_decode_list_lyrics_search_candidate(
    SseDeserializer deserializer,
  );

  @protected
  List<MediaKind> sse_decode_list_media_kind(SseDeserializer deserializer);

  @protected
  List<MediaRef> sse_decode_list_media_ref(SseDeserializer deserializer);

  @protected
  List<OutputSinkTypeDescriptor> sse_decode_list_output_sink_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<PlaylistLite> sse_decode_list_playlist_lite(
    SseDeserializer deserializer,
  );

  @protected
  List<PluginDescriptor> sse_decode_list_plugin_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer);

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<QueueEntry> sse_decode_list_queue_entry(SseDeserializer deserializer);

  @protected
  List<QueueMetadataUpdate> sse_decode_list_queue_metadata_update(
    SseDeserializer deserializer,
  );

  @protected
  List<(TrackId, ProviderQueueMetadata)>
  sse_decode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_provider_queue_metadata(
    SseDeserializer deserializer,
  );

  @protected
  List<(TrackId, TrackPresentation)>
  sse_decode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_track_presentation(
    SseDeserializer deserializer,
  );

  @protected
  List<SourceCatalogTypeDescriptor>
  sse_decode_list_source_catalog_type_descriptor(SseDeserializer deserializer);

  @protected
  List<TrackLite> sse_decode_list_track_lite(SseDeserializer deserializer);

  @protected
  LogBatch sse_decode_log_batch(SseDeserializer deserializer);

  @protected
  LogPage sse_decode_log_page(SseDeserializer deserializer);

  @protected
  LogRecord sse_decode_log_record(SseDeserializer deserializer);

  @protected
  LyricLine sse_decode_lyric_line(SseDeserializer deserializer);

  @protected
  LyricsDoc sse_decode_lyrics_doc(SseDeserializer deserializer);

  @protected
  LyricsEvent sse_decode_lyrics_event(SseDeserializer deserializer);

  @protected
  LyricsProviderTypeDescriptor sse_decode_lyrics_provider_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  LyricsQuery sse_decode_lyrics_query(SseDeserializer deserializer);

  @protected
  LyricsSearchCandidate sse_decode_lyrics_search_candidate(
    SseDeserializer deserializer,
  );

  @protected
  MediaKind sse_decode_media_kind(SseDeserializer deserializer);

  @protected
  MediaRef sse_decode_media_ref(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AppError? sse_decode_opt_box_autoadd_app_error(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  MediaRef? sse_decode_opt_box_autoadd_media_ref(SseDeserializer deserializer);

  @protected
  QueueProviderTrack? sse_decode_opt_box_autoadd_queue_provider_track(
    SseDeserializer deserializer,
  );

  @protected
  TrackCover? sse_decode_opt_box_autoadd_track_cover(
    SseDeserializer deserializer,
  );

  @protected
  TrackDecodeInfo? sse_decode_opt_box_autoadd_track_decode_info(
    SseDeserializer deserializer,
  );

  @protected
  TrackLite? sse_decode_opt_box_autoadd_track_lite(
    SseDeserializer deserializer,
  );

  @protected
  TrackPresentation? sse_decode_opt_box_autoadd_track_presentation(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  OutputSinkRoute sse_decode_output_sink_route(SseDeserializer deserializer);

  @protected
  OutputSinkTypeDescriptor sse_decode_output_sink_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  PlaybackLatency sse_decode_playback_latency(SseDeserializer deserializer);

  @protected
  PlaybackQueue sse_decode_playback_queue(SseDeserializer deserializer);

  @protected
  PlaybackSnapshot sse_decode_playback_snapshot(SseDeserializer deserializer);

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer);

  @protected
  PlaylistLite sse_decode_playlist_lite(SseDeserializer deserializer);

  @protected
  PluginDescriptor sse_decode_plugin_descriptor(SseDeserializer deserializer);

  @protected
  ProviderQueueMetadata sse_decode_provider_queue_metadata(
    SseDeserializer deserializer,
  );

  @protected
  QueueEntry sse_decode_queue_entry(SseDeserializer deserializer);

  @protected
  QueueMetadataUpdate sse_decode_queue_metadata_update(
    SseDeserializer deserializer,
  );

  @protected
  QueueProviderTrack sse_decode_queue_provider_track(
    SseDeserializer deserializer,
  );

  @protected
  QueueRepeatMode sse_decode_queue_repeat_mode(SseDeserializer deserializer);

  @protected
  (TrackId, ProviderQueueMetadata)
  sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_provider_queue_metadata(
    SseDeserializer deserializer,
  );

  @protected
  (TrackId, TrackPresentation)
  sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_track_presentation(
    SseDeserializer deserializer,
  );

  @protected
  ResampleQuality sse_decode_resample_quality(SseDeserializer deserializer);

  @protected
  SourceCatalogTypeDescriptor sse_decode_source_catalog_type_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  TrackCover sse_decode_track_cover(SseDeserializer deserializer);

  @protected
  TrackCoverKind sse_decode_track_cover_kind(SseDeserializer deserializer);

  @protected
  TrackDecodeInfo sse_decode_track_decode_info(SseDeserializer deserializer);

  @protected
  TrackLite sse_decode_track_lite(SseDeserializer deserializer);

  @protected
  TrackPresentation sse_decode_track_presentation(SseDeserializer deserializer);

  @protected
  TranscodeProgressEvent sse_decode_transcode_progress_event(
    SseDeserializer deserializer,
  );

  @protected
  TranscodeTrackLocalRequest sse_decode_transcode_track_local_request(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    LocalCatalog self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    PlayerCatalog self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    PlayerService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
    PlayerServiceError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    TrackId self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    LocalCatalog self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    PlayerCatalog self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    PlayerService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Map_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId_provider_queue_metadata_None(
    Map<TrackId, ProviderQueueMetadata> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    LocalCatalog self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    PlayerCatalog self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    PlayerService self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
    PlayerServiceError self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    TrackId self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_event_Sse(
    RustStreamSink<Event> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_library_event_Sse(
    RustStreamSink<LibraryEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_batch_Sse(
    RustStreamSink<LogBatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_lyrics_event_Sse(
    RustStreamSink<LyricsEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_playback_queue_Sse(
    RustStreamSink<PlaybackQueue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_transcode_progress_event_Sse(
    RustStreamSink<TranscodeProgressEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_app_error(AppError self, SseSerializer serializer);

  @protected
  void sse_encode_audio_backend(AudioBackend self, SseSerializer serializer);

  @protected
  void sse_encode_audio_device(AudioDevice self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_app_error(
    AppError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_catalog_query(
    CatalogQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_dlna_renderer(
    DlnaRenderer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_log_record(
    LogRecord self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lyrics_doc(
    LyricsDoc self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_lyrics_query(
    LyricsQuery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_media_ref(
    MediaRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_output_sink_route(
    OutputSinkRoute self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_queue_provider_track(
    QueueProviderTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_cover(
    TrackCover self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_decode_info(
    TrackDecodeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_lite(
    TrackLite self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_track_presentation(
    TrackPresentation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_transcode_track_local_request(
    TranscodeTrackLocalRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_item(CatalogItem self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_page(CatalogPage self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_query(CatalogQuery self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_sort(CatalogSort self, SseSerializer serializer);

  @protected
  void sse_encode_dlna_http_server_info(
    DlnaHttpServerInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_position_info(
    DlnaPositionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_renderer(DlnaRenderer self, SseSerializer serializer);

  @protected
  void sse_encode_dlna_ssdp_device(
    DlnaSsdpDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_transport_info(
    DlnaTransportInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dsp_chain_item(DspChainItem self, SseSerializer serializer);

  @protected
  void sse_encode_dsp_type_descriptor(
    DspTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_encoder_type_descriptor(
    EncoderTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_error_category(ErrorCategory self, SseSerializer serializer);

  @protected
  void sse_encode_event(Event self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_lfe_mode(LfeMode self, SseSerializer serializer);

  @protected
  void sse_encode_library_event(LibraryEvent self, SseSerializer serializer);

  @protected
  void sse_encode_library_source(LibrarySource self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    List<TrackId> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_device(
    List<AudioDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_catalog_item(
    List<CatalogItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_catalog_sort(
    List<CatalogSort> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dlna_renderer(
    List<DlnaRenderer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dlna_ssdp_device(
    List<DlnaSsdpDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dsp_chain_item(
    List<DspChainItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dsp_type_descriptor(
    List<DspTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_encoder_type_descriptor(
    List<EncoderTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_library_source(
    List<LibrarySource> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_log_record(
    List<LogRecord> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lyric_line(
    List<LyricLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lyrics_provider_type_descriptor(
    List<LyricsProviderTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_lyrics_search_candidate(
    List<LyricsSearchCandidate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_kind(
    List<MediaKind> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_media_ref(List<MediaRef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_output_sink_type_descriptor(
    List<OutputSinkTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_playlist_lite(
    List<PlaylistLite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_plugin_descriptor(
    List<PluginDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_i_64_strict(
    Int64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_queue_entry(
    List<QueueEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_queue_metadata_update(
    List<QueueMetadataUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_provider_queue_metadata(
    List<(TrackId, ProviderQueueMetadata)> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_list_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_track_presentation(
    List<(TrackId, TrackPresentation)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_source_catalog_type_descriptor(
    List<SourceCatalogTypeDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track_lite(
    List<TrackLite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_batch(LogBatch self, SseSerializer serializer);

  @protected
  void sse_encode_log_page(LogPage self, SseSerializer serializer);

  @protected
  void sse_encode_log_record(LogRecord self, SseSerializer serializer);

  @protected
  void sse_encode_lyric_line(LyricLine self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_doc(LyricsDoc self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_event(LyricsEvent self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_provider_type_descriptor(
    LyricsProviderTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_lyrics_query(LyricsQuery self, SseSerializer serializer);

  @protected
  void sse_encode_lyrics_search_candidate(
    LyricsSearchCandidate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_media_kind(MediaKind self, SseSerializer serializer);

  @protected
  void sse_encode_media_ref(MediaRef self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_app_error(
    AppError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_media_ref(
    MediaRef? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_queue_provider_track(
    QueueProviderTrack? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_track_cover(
    TrackCover? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_track_decode_info(
    TrackDecodeInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_track_lite(
    TrackLite? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_track_presentation(
    TrackPresentation? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_output_sink_route(
    OutputSinkRoute self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_output_sink_type_descriptor(
    OutputSinkTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_latency(
    PlaybackLatency self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_playback_queue(PlaybackQueue self, SseSerializer serializer);

  @protected
  void sse_encode_playback_snapshot(
    PlaybackSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer);

  @protected
  void sse_encode_playlist_lite(PlaylistLite self, SseSerializer serializer);

  @protected
  void sse_encode_plugin_descriptor(
    PluginDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_provider_queue_metadata(
    ProviderQueueMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_queue_entry(QueueEntry self, SseSerializer serializer);

  @protected
  void sse_encode_queue_metadata_update(
    QueueMetadataUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_queue_provider_track(
    QueueProviderTrack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_queue_repeat_mode(
    QueueRepeatMode self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_provider_queue_metadata(
    (TrackId, ProviderQueueMetadata) self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_track_id_track_presentation(
    (TrackId, TrackPresentation) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_resample_quality(
    ResampleQuality self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_source_catalog_type_descriptor(
    SourceCatalogTypeDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_cover(TrackCover self, SseSerializer serializer);

  @protected
  void sse_encode_track_cover_kind(
    TrackCoverKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_decode_info(
    TrackDecodeInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_track_lite(TrackLite self, SseSerializer serializer);

  @protected
  void sse_encode_track_presentation(
    TrackPresentation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcode_progress_event(
    TranscodeProgressEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_transcode_track_local_request(
    TranscodeTrackLocalRequest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class StellatuneApiWire implements BaseWire {
  factory StellatuneApiWire.fromExternalLibrary(ExternalLibrary lib) =>
      StellatuneApiWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  StellatuneApiWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalogPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalogPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalogPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalog =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerLocalCatalogPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalogPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalogPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalogPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalog =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerCatalogPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServicePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServicePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerService =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServicePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceErrorPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceError =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerPlayerServiceErrorPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackIdPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackIdPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackIdPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackId =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerTrackIdPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
