// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/stellatune_core.dart';

/// Main entrypoint of the Rust API
class StellatuneApi
    extends
        BaseEntrypoint<
          StellatuneApiApi,
          StellatuneApiApiImpl,
          StellatuneApiWire
        > {
  @internal
  static final instance = StellatuneApi._();

  StellatuneApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    StellatuneApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required StellatuneApiApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<StellatuneApiApiImpl, StellatuneApiWire>
  get apiImplConstructor => StellatuneApiApiImpl.new;

  @override
  WireConstructor<StellatuneApiWire> get wireConstructor =>
      StellatuneApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 2146619676;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'stellatune_ffi',
        ioDirectory: '../../crates/stellatune-ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class StellatuneApiApi extends BaseApi {
  Future<CoreService> crateApiCreateCoreService();

  Stream<Event> crateApiEventsStream({required CoreService service});

  Future<void> crateApiSendCommand({
    required CoreService service,
    required Command cmd,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CoreService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CoreService;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_CoreServicePtr;
}

class StellatuneApiApiImpl extends StellatuneApiApiImplPlatform
    implements StellatuneApiApi {
  StellatuneApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<CoreService> crateApiCreateCoreService() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_RustOpaque_CoreService,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreateCoreServiceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreateCoreServiceConstMeta =>
      const TaskConstMeta(debugName: "create_core_service", argNames: []);

  @override
  Stream<Event> crateApiEventsStream({required CoreService service}) {
    final sink = RustStreamSink<Event>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_RustOpaque_CoreService(service, serializer);
            sse_encode_StreamSink_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEventsStreamConstMeta,
          argValues: [service, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEventsStreamConstMeta => const TaskConstMeta(
    debugName: "events_stream",
    argNames: ["service", "sink"],
  );

  @override
  Future<void> crateApiSendCommand({
    required CoreService service,
    required Command cmd,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_CoreService(service, serializer);
          sse_encode_box_autoadd_command(cmd, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSendCommandConstMeta,
        argValues: [service, cmd],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSendCommandConstMeta => const TaskConstMeta(
    debugName: "send_command",
    argNames: ["service", "cmd"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_CoreService =>
      wire.rust_arc_increment_strong_count_RustOpaque_CoreService;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_CoreService =>
      wire.rust_arc_decrement_strong_count_RustOpaque_CoreService;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  CoreService dco_decode_RustOpaque_CoreService(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CoreServiceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<Event> dco_decode_StreamSink_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Command dco_decode_box_autoadd_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_command(raw);
  }

  @protected
  Command dco_decode_command(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Command_Play();
      case 1:
        return Command_Pause();
      case 2:
        return Command_Stop();
      case 3:
        return Command_Seek(ms: dco_decode_i_64(raw[1]));
      case 4:
        return Command_LoadTrack(path: dco_decode_String(raw[1]));
      case 5:
        return Command_SetVolume(linear: dco_decode_f_64(raw[1]));
      case 6:
        return Command_SetMuted(muted: dco_decode_bool(raw[1]));
      case 7:
        return Command_Enqueue(path: dco_decode_String(raw[1]));
      case 8:
        return Command_Next();
      case 9:
        return Command_Previous();
      case 10:
        return Command_Shutdown();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  Event dco_decode_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Event_StateChanged(state: dco_decode_player_state(raw[1]));
      case 1:
        return Event_Position(ms: dco_decode_i_64(raw[1]));
      case 2:
        return Event_TrackChanged(path: dco_decode_String(raw[1]));
      case 3:
        return Event_Error(message: dco_decode_String(raw[1]));
      case 4:
        return Event_Log(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PlayerState dco_decode_player_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerState.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  CoreService sse_decode_RustOpaque_CoreService(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return CoreServiceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<Event> sse_decode_StreamSink_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Command sse_decode_box_autoadd_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_command(deserializer));
  }

  @protected
  Command sse_decode_command(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return Command_Play();
      case 1:
        return Command_Pause();
      case 2:
        return Command_Stop();
      case 3:
        var var_ms = sse_decode_i_64(deserializer);
        return Command_Seek(ms: var_ms);
      case 4:
        var var_path = sse_decode_String(deserializer);
        return Command_LoadTrack(path: var_path);
      case 5:
        var var_linear = sse_decode_f_64(deserializer);
        return Command_SetVolume(linear: var_linear);
      case 6:
        var var_muted = sse_decode_bool(deserializer);
        return Command_SetMuted(muted: var_muted);
      case 7:
        var var_path = sse_decode_String(deserializer);
        return Command_Enqueue(path: var_path);
      case 8:
        return Command_Next();
      case 9:
        return Command_Previous();
      case 10:
        return Command_Shutdown();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  Event sse_decode_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_state = sse_decode_player_state(deserializer);
        return Event_StateChanged(state: var_state);
      case 1:
        var var_ms = sse_decode_i_64(deserializer);
        return Event_Position(ms: var_ms);
      case 2:
        var var_path = sse_decode_String(deserializer);
        return Event_TrackChanged(path: var_path);
      case 3:
        var var_message = sse_decode_String(deserializer);
        return Event_Error(message: var_message);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return Event_Log(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlayerState.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_RustOpaque_CoreService(
    CoreService self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as CoreServiceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_event_Sse(
    RustStreamSink<Event> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_command(Command self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_command(self, serializer);
  }

  @protected
  void sse_encode_command(Command self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Command_Play():
        sse_encode_i_32(0, serializer);
      case Command_Pause():
        sse_encode_i_32(1, serializer);
      case Command_Stop():
        sse_encode_i_32(2, serializer);
      case Command_Seek(ms: final ms):
        sse_encode_i_32(3, serializer);
        sse_encode_i_64(ms, serializer);
      case Command_LoadTrack(path: final path):
        sse_encode_i_32(4, serializer);
        sse_encode_String(path, serializer);
      case Command_SetVolume(linear: final linear):
        sse_encode_i_32(5, serializer);
        sse_encode_f_64(linear, serializer);
      case Command_SetMuted(muted: final muted):
        sse_encode_i_32(6, serializer);
        sse_encode_bool(muted, serializer);
      case Command_Enqueue(path: final path):
        sse_encode_i_32(7, serializer);
        sse_encode_String(path, serializer);
      case Command_Next():
        sse_encode_i_32(8, serializer);
      case Command_Previous():
        sse_encode_i_32(9, serializer);
      case Command_Shutdown():
        sse_encode_i_32(10, serializer);
    }
  }

  @protected
  void sse_encode_event(Event self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Event_StateChanged(state: final state):
        sse_encode_i_32(0, serializer);
        sse_encode_player_state(state, serializer);
      case Event_Position(ms: final ms):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(ms, serializer);
      case Event_TrackChanged(path: final path):
        sse_encode_i_32(2, serializer);
        sse_encode_String(path, serializer);
      case Event_Error(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
      case Event_Log(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class CoreServiceImpl extends RustOpaque implements CoreService {
  // Not to be used by end users
  CoreServiceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  CoreServiceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        StellatuneApi.instance.api.rust_arc_increment_strong_count_CoreService,
    rustArcDecrementStrongCount:
        StellatuneApi.instance.api.rust_arc_decrement_strong_count_CoreService,
    rustArcDecrementStrongCountPtr: StellatuneApi
        .instance
        .api
        .rust_arc_decrement_strong_count_CoreServicePtr,
  );
}
