// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/stellatune_core.dart';

/// Main entrypoint of the Rust API
class StellatuneApi
    extends
        BaseEntrypoint<
          StellatuneApiApi,
          StellatuneApiApiImpl,
          StellatuneApiWire
        > {
  @internal
  static final instance = StellatuneApi._();

  StellatuneApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    StellatuneApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required StellatuneApiApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<StellatuneApiApiImpl, StellatuneApiWire>
  get apiImplConstructor => StellatuneApiApiImpl.new;

  @override
  WireConstructor<StellatuneApiWire> get wireConstructor =>
      StellatuneApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 741439296;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'stellatune_ffi',
        ioDirectory: '../../crates/stellatune-ffi/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class StellatuneApiApi extends BaseApi {
  Future<Player> crateApiCreatePlayer();

  Stream<Event> crateApiEvents({required Player player});

  Future<void> crateApiLoad({required Player player, required String path});

  Future<void> crateApiPause({required Player player});

  Future<void> crateApiPlay({required Player player});

  Future<void> crateApiStop({required Player player});

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_Player;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_Player;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PlayerPtr;
}

class StellatuneApiApiImpl extends StellatuneApiApiImplPlatform
    implements StellatuneApiApi {
  StellatuneApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Player> crateApiCreatePlayer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_RustOpaque_Player,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCreatePlayerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCreatePlayerConstMeta =>
      const TaskConstMeta(debugName: "create_player", argNames: []);

  @override
  Stream<Event> crateApiEvents({required Player player}) {
    final sink = RustStreamSink<Event>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_RustOpaque_Player(player, serializer);
            sse_encode_StreamSink_event_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 2,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_AnyhowException,
          ),
          constMeta: kCrateApiEventsConstMeta,
          argValues: [player, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiEventsConstMeta =>
      const TaskConstMeta(debugName: "events", argNames: ["player", "sink"]);

  @override
  Future<void> crateApiLoad({required Player player, required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Player(player, serializer);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiLoadConstMeta,
        argValues: [player, path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLoadConstMeta =>
      const TaskConstMeta(debugName: "load", argNames: ["player", "path"]);

  @override
  Future<void> crateApiPause({required Player player}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Player(player, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPauseConstMeta,
        argValues: [player],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPauseConstMeta =>
      const TaskConstMeta(debugName: "pause", argNames: ["player"]);

  @override
  Future<void> crateApiPlay({required Player player}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Player(player, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayConstMeta,
        argValues: [player],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayConstMeta =>
      const TaskConstMeta(debugName: "play", argNames: ["player"]);

  @override
  Future<void> crateApiStop({required Player player}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_RustOpaque_Player(player, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiStopConstMeta,
        argValues: [player],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiStopConstMeta =>
      const TaskConstMeta(debugName: "stop", argNames: ["player"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_Player =>
      wire.rust_arc_increment_strong_count_RustOpaque_Player;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_Player =>
      wire.rust_arc_decrement_strong_count_RustOpaque_Player;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  Player dco_decode_RustOpaque_Player(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<Event> dco_decode_StreamSink_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  Event dco_decode_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return Event_StateChanged(state: dco_decode_player_state(raw[1]));
      case 1:
        return Event_Position(ms: dco_decode_i_64(raw[1]));
      case 2:
        return Event_TrackChanged(path: dco_decode_String(raw[1]));
      case 3:
        return Event_Error(message: dco_decode_String(raw[1]));
      case 4:
        return Event_Log(message: dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  PlayerState dco_decode_player_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PlayerState.values[raw as int];
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  Player sse_decode_RustOpaque_Player(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return PlayerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<Event> sse_decode_StreamSink_event_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  Event sse_decode_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_state = sse_decode_player_state(deserializer);
        return Event_StateChanged(state: var_state);
      case 1:
        var var_ms = sse_decode_i_64(deserializer);
        return Event_Position(ms: var_ms);
      case 2:
        var var_path = sse_decode_String(deserializer);
        return Event_TrackChanged(path: var_path);
      case 3:
        var var_message = sse_decode_String(deserializer);
        return Event_Error(message: var_message);
      case 4:
        var var_message = sse_decode_String(deserializer);
        return Event_Log(message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PlayerState.values[inner];
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_RustOpaque_Player(Player self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as PlayerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_event_Sse(
    RustStreamSink<Event> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_event,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_event(Event self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case Event_StateChanged(state: final state):
        sse_encode_i_32(0, serializer);
        sse_encode_player_state(state, serializer);
      case Event_Position(ms: final ms):
        sse_encode_i_32(1, serializer);
        sse_encode_i_64(ms, serializer);
      case Event_TrackChanged(path: final path):
        sse_encode_i_32(2, serializer);
        sse_encode_String(path, serializer);
      case Event_Error(message: final message):
        sse_encode_i_32(3, serializer);
        sse_encode_String(message, serializer);
      case Event_Log(message: final message):
        sse_encode_i_32(4, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}

@sealed
class PlayerImpl extends RustOpaque implements Player {
  // Not to be used by end users
  PlayerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  PlayerImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        StellatuneApi.instance.api.rust_arc_increment_strong_count_Player,
    rustArcDecrementStrongCount:
        StellatuneApi.instance.api.rust_arc_decrement_strong_count_Player,
    rustArcDecrementStrongCountPtr:
        StellatuneApi.instance.api.rust_arc_decrement_strong_count_PlayerPtr,
  );
}
