// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'third_party/stellatune_core.dart';

abstract class StellatuneApiApiImplPlatform
    extends BaseApiImpl<StellatuneApiWire> {
  StellatuneApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_LibraryPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_LibraryPtr;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_PlayerPtr =>
      wire._rust_arc_decrement_strong_count_RustOpaque_PlayerPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Library dco_decode_RustOpaque_Library(dynamic raw);

  @protected
  Player dco_decode_RustOpaque_Player(dynamic raw);

  @protected
  RustStreamSink<Event> dco_decode_StreamSink_event_Sse(dynamic raw);

  @protected
  RustStreamSink<LibraryEvent> dco_decode_StreamSink_library_event_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DlnaRenderer dco_decode_box_autoadd_dlna_renderer(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  DlnaHttpServerInfo dco_decode_dlna_http_server_info(dynamic raw);

  @protected
  DlnaPositionInfo dco_decode_dlna_position_info(dynamic raw);

  @protected
  DlnaRenderer dco_decode_dlna_renderer(dynamic raw);

  @protected
  DlnaSsdpDevice dco_decode_dlna_ssdp_device(dynamic raw);

  @protected
  DlnaTransportInfo dco_decode_dlna_transport_info(dynamic raw);

  @protected
  Event dco_decode_event(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LibraryEvent dco_decode_library_event(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DlnaRenderer> dco_decode_list_dlna_renderer(dynamic raw);

  @protected
  List<DlnaSsdpDevice> dco_decode_list_dlna_ssdp_device(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<TrackLite> dco_decode_list_track_lite(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  PlayerState dco_decode_player_state(dynamic raw);

  @protected
  TrackLite dco_decode_track_lite(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Library sse_decode_RustOpaque_Library(SseDeserializer deserializer);

  @protected
  Player sse_decode_RustOpaque_Player(SseDeserializer deserializer);

  @protected
  RustStreamSink<Event> sse_decode_StreamSink_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LibraryEvent> sse_decode_StreamSink_library_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DlnaRenderer sse_decode_box_autoadd_dlna_renderer(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  DlnaHttpServerInfo sse_decode_dlna_http_server_info(
    SseDeserializer deserializer,
  );

  @protected
  DlnaPositionInfo sse_decode_dlna_position_info(SseDeserializer deserializer);

  @protected
  DlnaRenderer sse_decode_dlna_renderer(SseDeserializer deserializer);

  @protected
  DlnaSsdpDevice sse_decode_dlna_ssdp_device(SseDeserializer deserializer);

  @protected
  DlnaTransportInfo sse_decode_dlna_transport_info(
    SseDeserializer deserializer,
  );

  @protected
  Event sse_decode_event(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LibraryEvent sse_decode_library_event(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DlnaRenderer> sse_decode_list_dlna_renderer(
    SseDeserializer deserializer,
  );

  @protected
  List<DlnaSsdpDevice> sse_decode_list_dlna_ssdp_device(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<TrackLite> sse_decode_list_track_lite(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  PlayerState sse_decode_player_state(SseDeserializer deserializer);

  @protected
  TrackLite sse_decode_track_lite(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_RustOpaque_Library(Library self, SseSerializer serializer);

  @protected
  void sse_encode_RustOpaque_Player(Player self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_event_Sse(
    RustStreamSink<Event> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_library_event_Sse(
    RustStreamSink<LibraryEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dlna_renderer(
    DlnaRenderer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_dlna_http_server_info(
    DlnaHttpServerInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_position_info(
    DlnaPositionInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_renderer(DlnaRenderer self, SseSerializer serializer);

  @protected
  void sse_encode_dlna_ssdp_device(
    DlnaSsdpDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dlna_transport_info(
    DlnaTransportInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_event(Event self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_library_event(LibraryEvent self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_dlna_renderer(
    List<DlnaRenderer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dlna_ssdp_device(
    List<DlnaSsdpDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_track_lite(
    List<TrackLite> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_player_state(PlayerState self, SseSerializer serializer);

  @protected
  void sse_encode_track_lite(TrackLite self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class StellatuneApiWire implements BaseWire {
  factory StellatuneApiWire.fromExternalLibrary(ExternalLibrary lib) =>
      StellatuneApiWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  StellatuneApiWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void rust_arc_increment_strong_count_RustOpaque_Library(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_Library(ptr);
  }

  late final _rust_arc_increment_strong_count_RustOpaque_LibraryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_increment_strong_count_RustOpaque_Library',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_Library =
      _rust_arc_increment_strong_count_RustOpaque_LibraryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_Library(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_Library(ptr);
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_LibraryPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_decrement_strong_count_RustOpaque_Library',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_Library =
      _rust_arc_decrement_strong_count_RustOpaque_LibraryPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_increment_strong_count_RustOpaque_Player(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_Player(ptr);
  }

  late final _rust_arc_increment_strong_count_RustOpaque_PlayerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_increment_strong_count_RustOpaque_Player',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_Player =
      _rust_arc_increment_strong_count_RustOpaque_PlayerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void rust_arc_decrement_strong_count_RustOpaque_Player(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_Player(ptr);
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_PlayerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_stellatune_rust_arc_decrement_strong_count_RustOpaque_Player',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_Player =
      _rust_arc_decrement_strong_count_RustOpaque_PlayerPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
