// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class DlnaHttpServerInfo {
  final String listenAddr;
  final String baseUrl;

  const DlnaHttpServerInfo({required this.listenAddr, required this.baseUrl});

  @override
  int get hashCode => listenAddr.hashCode ^ baseUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DlnaHttpServerInfo &&
          runtimeType == other.runtimeType &&
          listenAddr == other.listenAddr &&
          baseUrl == other.baseUrl;
}

class DlnaPositionInfo {
  final BigInt relTimeMs;
  final BigInt? trackDurationMs;

  const DlnaPositionInfo({required this.relTimeMs, this.trackDurationMs});

  @override
  int get hashCode => relTimeMs.hashCode ^ trackDurationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DlnaPositionInfo &&
          runtimeType == other.runtimeType &&
          relTimeMs == other.relTimeMs &&
          trackDurationMs == other.trackDurationMs;
}

class DlnaRenderer {
  final String usn;
  final String location;
  final String friendlyName;
  final String? avTransportControlUrl;
  final String? avTransportServiceType;
  final String? renderingControlUrl;
  final String? renderingControlServiceType;

  const DlnaRenderer({
    required this.usn,
    required this.location,
    required this.friendlyName,
    this.avTransportControlUrl,
    this.avTransportServiceType,
    this.renderingControlUrl,
    this.renderingControlServiceType,
  });

  @override
  int get hashCode =>
      usn.hashCode ^
      location.hashCode ^
      friendlyName.hashCode ^
      avTransportControlUrl.hashCode ^
      avTransportServiceType.hashCode ^
      renderingControlUrl.hashCode ^
      renderingControlServiceType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DlnaRenderer &&
          runtimeType == other.runtimeType &&
          usn == other.usn &&
          location == other.location &&
          friendlyName == other.friendlyName &&
          avTransportControlUrl == other.avTransportControlUrl &&
          avTransportServiceType == other.avTransportServiceType &&
          renderingControlUrl == other.renderingControlUrl &&
          renderingControlServiceType == other.renderingControlServiceType;
}

class DlnaSsdpDevice {
  final String usn;
  final String st;
  final String location;
  final String? server;

  const DlnaSsdpDevice({
    required this.usn,
    required this.st,
    required this.location,
    this.server,
  });

  @override
  int get hashCode =>
      usn.hashCode ^ st.hashCode ^ location.hashCode ^ server.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DlnaSsdpDevice &&
          runtimeType == other.runtimeType &&
          usn == other.usn &&
          st == other.st &&
          location == other.location &&
          server == other.server;
}

class DlnaTransportInfo {
  final String currentTransportState;
  final String? currentTransportStatus;
  final String? currentSpeed;

  const DlnaTransportInfo({
    required this.currentTransportState,
    this.currentTransportStatus,
    this.currentSpeed,
  });

  @override
  int get hashCode =>
      currentTransportState.hashCode ^
      currentTransportStatus.hashCode ^
      currentSpeed.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DlnaTransportInfo &&
          runtimeType == other.runtimeType &&
          currentTransportState == other.currentTransportState &&
          currentTransportStatus == other.currentTransportStatus &&
          currentSpeed == other.currentSpeed;
}
