# Build-time only. No system Node installation is needed to prepare the runtime.
cmake_minimum_required(VERSION 3.14)
foreach(required NODE_TARGET NODE_CACHE NODE_DEST)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "${required} is required")
  endif()
endforeach()
set(NODE_VERSION "24.20.0")
set(hash_win_x64 "6cac9ffbca8f6a47091e4b5c772e0606049c3871cb67d900c0cedde630e545ba")
set(hash_win_arm64 "31c6799744de8a54601643098040c68c3697e56c94e407d61d0e5fa5f34191d7")
set(hash_linux_x64 "855d581f8a4eb1a8117e3426de25fe02770592febcfb31369aee1ffbfee9e8ec")
set(hash_linux_arm64 "3515603e2487879a39bc75716f1a2affd027500c64ba50e845cf72cb33219013")
set(hash_darwin_x64 "9e5b2644cf107befb6aefca676b96d3296bc10138096f022ed378d6233ed81f4")
set(hash_darwin_arm64 "40e5607e5ecb3db9192723776da2d75d966260fc74a7a9e731c1bd67dda96bc8")
string(REPLACE "-" "_" hash_key "${NODE_TARGET}")
set(expected_hash "${hash_${hash_key}}")
if(NOT expected_hash)
  message(FATAL_ERROR "Unsupported Node platform: ${NODE_TARGET}")
endif()
set(stem "node-v${NODE_VERSION}-${NODE_TARGET}")
if(NODE_TARGET MATCHES "^win-")
  set(archive_name "${stem}.zip")
  set(binary "node.exe")
  set(binary_source "node.exe")
else()
  set(archive_name "${stem}.tar.gz")
  set(binary "node")
  set(binary_source "bin/node")
endif()
file(MAKE_DIRECTORY "${NODE_CACHE}" "${NODE_DEST}")
file(LOCK "${NODE_CACHE}/${NODE_TARGET}.lock" GUARD PROCESS TIMEOUT 300)
set(archive "${NODE_CACHE}/${archive_name}")
if(EXISTS "${archive}")
  file(SHA256 "${archive}" actual_hash)
  if(NOT actual_hash STREQUAL expected_hash)
    message(FATAL_ERROR "Node cache checksum mismatch: ${archive}; remove this archive and retry")
  endif()
else()
  message(STATUS "Downloading Node ${NODE_VERSION} (${NODE_TARGET})")
  file(DOWNLOAD "https://nodejs.org/dist/v${NODE_VERSION}/${archive_name}"
    "${archive}.download" TLS_VERIFY ON TIMEOUT 300
    EXPECTED_HASH "SHA256=${expected_hash}" STATUS download_status)
  list(GET download_status 0 download_code)
  if(NOT download_code EQUAL 0)
    message(FATAL_ERROR "Node download failed: ${download_status}")
  endif()
  file(RENAME "${archive}.download" "${archive}")
endif()
set(extract_dir "${NODE_CACHE}/${NODE_TARGET}-${NODE_VERSION}")
file(MAKE_DIRECTORY "${extract_dir}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${archive}"
  "${stem}/${binary_source}" "${stem}/LICENSE"
  WORKING_DIRECTORY "${extract_dir}" RESULT_VARIABLE unpack_result)
if(NOT unpack_result EQUAL 0)
  message(FATAL_ERROR "Failed to extract ${archive}")
endif()
if(NODE_TARGET MATCHES "^darwin-(.+)$")
  set(binary "node-${CMAKE_MATCH_1}")
endif()
configure_file("${extract_dir}/${stem}/${binary_source}" "${NODE_DEST}/${binary}" COPYONLY)
configure_file("${extract_dir}/${stem}/LICENSE" "${NODE_DEST}/NODE-LICENSE" COPYONLY)
file(WRITE "${NODE_DEST}/NODE-VERSION" "${NODE_VERSION}\n")
foreach(script runner.mjs host-client.mjs ui-server.mjs)
  configure_file("${CMAKE_CURRENT_LIST_DIR}/${script}" "${NODE_DEST}/${script}" COPYONLY)
endforeach()
