// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../third_party/stellatune_library.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `navigation_result`, `project`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

Future<PlaybackQueue> playbackQueue() =>
    StellatuneApi.instance.api.crateApiPlayerQueuePlaybackQueue();

Future<PlaybackQueue> replaceQueue({required Uint64List trackIds}) =>
    StellatuneApi.instance.api.crateApiPlayerQueueReplaceQueue(
      trackIds: trackIds,
    );

Future<PlaybackQueue> appendQueue({required Uint64List trackIds}) =>
    StellatuneApi.instance.api.crateApiPlayerQueueAppendQueue(
      trackIds: trackIds,
    );

Future<PlaybackQueue> removeQueueItems({required Uint64List itemIds}) =>
    StellatuneApi.instance.api.crateApiPlayerQueueRemoveQueueItems(
      itemIds: itemIds,
    );

Future<PlaybackQueue> setQueueMode({
  required QueueRepeatMode repeat,
  required bool shuffle,
}) => StellatuneApi.instance.api.crateApiPlayerQueueSetQueueMode(
  repeat: repeat,
  shuffle: shuffle,
);

/// Returns false when a newer navigation intent superseded this request.
Future<bool> selectQueueItem({
  required BigInt itemId,
  required bool autoplay,
}) => StellatuneApi.instance.api.crateApiPlayerQueueSelectQueueItem(
  itemId: itemId,
  autoplay: autoplay,
);

Future<bool> nextQueueItem() =>
    StellatuneApi.instance.api.crateApiPlayerQueueNextQueueItem();

Future<bool> previousQueueItem() =>
    StellatuneApi.instance.api.crateApiPlayerQueuePreviousQueueItem();

class PlaybackQueue {
  final List<QueueEntry> items;
  final Uint64List order;
  final BigInt? currentItemId;
  final BigInt? requestedItemId;
  final QueueRepeatMode repeatMode;
  final bool shuffle;
  final BigInt revision;

  const PlaybackQueue({
    required this.items,
    required this.order,
    this.currentItemId,
    this.requestedItemId,
    required this.repeatMode,
    required this.shuffle,
    required this.revision,
  });

  @override
  int get hashCode =>
      items.hashCode ^
      order.hashCode ^
      currentItemId.hashCode ^
      requestedItemId.hashCode ^
      repeatMode.hashCode ^
      shuffle.hashCode ^
      revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackQueue &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          order == other.order &&
          currentItemId == other.currentItemId &&
          requestedItemId == other.requestedItemId &&
          repeatMode == other.repeatMode &&
          shuffle == other.shuffle &&
          revision == other.revision;
}

class QueueEntry {
  final BigInt itemId;
  final BigInt trackId;
  final PlatformInt64? localLibraryTrackId;
  final String? localPath;
  final TrackLite? localMetadata;

  const QueueEntry({
    required this.itemId,
    required this.trackId,
    this.localLibraryTrackId,
    this.localPath,
    this.localMetadata,
  });

  @override
  int get hashCode =>
      itemId.hashCode ^
      trackId.hashCode ^
      localLibraryTrackId.hashCode ^
      localPath.hashCode ^
      localMetadata.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is QueueEntry &&
          runtimeType == other.runtimeType &&
          itemId == other.itemId &&
          trackId == other.trackId &&
          localLibraryTrackId == other.localLibraryTrackId &&
          localPath == other.localPath &&
          localMetadata == other.localMetadata;
}

enum QueueRepeatMode { off, all, one }
