// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `clear_transcode_cancel_flag`, `emit_transcode_event`, `ensure_transcode_not_canceled`, `estimate_total_frames`, `new`, `normalize_optional_json_opt`, `normalize_optional_json`, `register_transcode_cancel_flag`, `run_transcode_track_local_blocking`, `shared_transcode_cancel_flags`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `TranscodeTaskContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Stream<TranscodeProgressEvent> transcodeTrackLocal({
  required TranscodeTrackLocalRequest request,
}) => StellatuneApi.instance.api.crateApiPlayerTranscodeTranscodeTrackLocal(
  request: request,
);

Future<void> transcodeCancel({required String taskId}) => StellatuneApi
    .instance
    .api
    .crateApiPlayerTranscodeTranscodeCancel(taskId: taskId);

class TranscodeTrackLocalRequest {
  final String taskId;
  final String sourcePath;
  final String outputPath;
  final String encoderPluginId;
  final String encoderTypeId;
  final String encoderConfigJson;
  final String? encoderOptionsJson;

  const TranscodeTrackLocalRequest({
    required this.taskId,
    required this.sourcePath,
    required this.outputPath,
    required this.encoderPluginId,
    required this.encoderTypeId,
    required this.encoderConfigJson,
    this.encoderOptionsJson,
  });

  @override
  int get hashCode =>
      taskId.hashCode ^
      sourcePath.hashCode ^
      outputPath.hashCode ^
      encoderPluginId.hashCode ^
      encoderTypeId.hashCode ^
      encoderConfigJson.hashCode ^
      encoderOptionsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscodeTrackLocalRequest &&
          runtimeType == other.runtimeType &&
          taskId == other.taskId &&
          sourcePath == other.sourcePath &&
          outputPath == other.outputPath &&
          encoderPluginId == other.encoderPluginId &&
          encoderTypeId == other.encoderTypeId &&
          encoderConfigJson == other.encoderConfigJson &&
          encoderOptionsJson == other.encoderOptionsJson;
}
