// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

// These functions are ignored because they have generic arguments: `config`, `config`, `metadata`, `set_metadata`, `target`, `with_config_target`, `with_config`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

enum AudioBackend { shared, wasapiExclusive }

class AudioDevice {
  final AudioBackend backend;
  final String id;
  final String name;

  const AudioDevice({
    required this.backend,
    required this.id,
    required this.name,
  });

  @override
  int get hashCode => backend.hashCode ^ id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioDevice &&
          runtimeType == other.runtimeType &&
          backend == other.backend &&
          id == other.id &&
          name == other.name;
}

class DspChainItem {
  final String pluginId;
  final String typeId;
  final String configJson;

  const DspChainItem({
    required this.pluginId,
    required this.typeId,
    required this.configJson,
  });

  @override
  int get hashCode => pluginId.hashCode ^ typeId.hashCode ^ configJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DspChainItem &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          typeId == other.typeId &&
          configJson == other.configJson;
}

class DspTypeDescriptor {
  final String pluginId;
  final String pluginName;
  final String typeId;
  final String displayName;
  final String configSchemaJson;
  final String defaultConfigJson;

  const DspTypeDescriptor({
    required this.pluginId,
    required this.pluginName,
    required this.typeId,
    required this.displayName,
    required this.configSchemaJson,
    required this.defaultConfigJson,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      pluginName.hashCode ^
      typeId.hashCode ^
      displayName.hashCode ^
      configSchemaJson.hashCode ^
      defaultConfigJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DspTypeDescriptor &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          pluginName == other.pluginName &&
          typeId == other.typeId &&
          displayName == other.displayName &&
          configSchemaJson == other.configSchemaJson &&
          defaultConfigJson == other.defaultConfigJson;
}

class EncoderTypeDescriptor {
  final String pluginId;
  final String pluginName;
  final String typeId;
  final String displayName;
  final String configSchemaJson;
  final String defaultConfigJson;

  const EncoderTypeDescriptor({
    required this.pluginId,
    required this.pluginName,
    required this.typeId,
    required this.displayName,
    required this.configSchemaJson,
    required this.defaultConfigJson,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      pluginName.hashCode ^
      typeId.hashCode ^
      displayName.hashCode ^
      configSchemaJson.hashCode ^
      defaultConfigJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EncoderTypeDescriptor &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          pluginName == other.pluginName &&
          typeId == other.typeId &&
          displayName == other.displayName &&
          configSchemaJson == other.configSchemaJson &&
          defaultConfigJson == other.defaultConfigJson;
}

@freezed
sealed class Event with _$Event {
  const Event._();

  const factory Event.stateChanged({required PlayerState state}) =
      Event_StateChanged;
  const factory Event.position({
    required PlatformInt64 ms,
    required BigInt trackId,
    required BigInt itemId,
    required BigInt sessionId,
  }) = Event_Position;
  const factory Event.trackChanged({
    required BigInt trackId,
    required BigInt itemId,
  }) = Event_TrackChanged;
  const factory Event.playbackEnded({
    required BigInt trackId,
    required BigInt itemId,
  }) = Event_PlaybackEnded;
  const factory Event.volumeChanged({
    required double volume,
    required BigInt seq,
  }) = Event_VolumeChanged;
  const factory Event.audioStart() = Event_AudioStart;
  const factory Event.audioEnd() = Event_AudioEnd;
  const factory Event.error({required String message}) = Event_Error;
  const factory Event.log({required String message}) = Event_Log;
}

enum LfeMode {
  mute,
  mixToFront;

  static Future<LfeMode> default_() =>
      StellatuneApi.instance.api.crateApiPlayerTypesLfeModeDefault();
}

class LyricsProviderTypeDescriptor {
  final String pluginId;
  final String pluginName;
  final String typeId;
  final String displayName;

  const LyricsProviderTypeDescriptor({
    required this.pluginId,
    required this.pluginName,
    required this.typeId,
    required this.displayName,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      pluginName.hashCode ^
      typeId.hashCode ^
      displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LyricsProviderTypeDescriptor &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          pluginName == other.pluginName &&
          typeId == other.typeId &&
          displayName == other.displayName;
}

class OutputSinkRoute {
  final String pluginId;
  final String typeId;
  final String configJson;
  final String targetJson;

  const OutputSinkRoute({
    required this.pluginId,
    required this.typeId,
    required this.configJson,
    required this.targetJson,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      typeId.hashCode ^
      configJson.hashCode ^
      targetJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutputSinkRoute &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          typeId == other.typeId &&
          configJson == other.configJson &&
          targetJson == other.targetJson;
}

class OutputSinkTypeDescriptor {
  final String pluginId;
  final String pluginName;
  final String typeId;
  final String displayName;
  final String configSchemaJson;
  final String defaultConfigJson;

  const OutputSinkTypeDescriptor({
    required this.pluginId,
    required this.pluginName,
    required this.typeId,
    required this.displayName,
    required this.configSchemaJson,
    required this.defaultConfigJson,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      pluginName.hashCode ^
      typeId.hashCode ^
      displayName.hashCode ^
      configSchemaJson.hashCode ^
      defaultConfigJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutputSinkTypeDescriptor &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          pluginName == other.pluginName &&
          typeId == other.typeId &&
          displayName == other.displayName &&
          configSchemaJson == other.configSchemaJson &&
          defaultConfigJson == other.defaultConfigJson;
}

enum PlaybackLatency {
  low,
  medium,
  high;

  static Future<PlaybackLatency> default_() =>
      StellatuneApi.instance.api.crateApiPlayerTypesPlaybackLatencyDefault();
}

class PlaybackSnapshot {
  final PlayerState state;
  final BigInt? trackId;
  final BigInt? itemId;
  final PlatformInt64? localLibraryTrackId;
  final PlatformInt64 positionMs;

  const PlaybackSnapshot({
    required this.state,
    this.trackId,
    this.itemId,
    this.localLibraryTrackId,
    required this.positionMs,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      trackId.hashCode ^
      itemId.hashCode ^
      localLibraryTrackId.hashCode ^
      positionMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PlaybackSnapshot &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          trackId == other.trackId &&
          itemId == other.itemId &&
          localLibraryTrackId == other.localLibraryTrackId &&
          positionMs == other.positionMs;
}

enum PlayerState { stopped, playing, paused, buffering }

class PluginDescriptor {
  final String id;
  final String name;

  const PluginDescriptor({required this.id, required this.name});

  @override
  int get hashCode => id.hashCode ^ name.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PluginDescriptor &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name;
}

enum ResampleQuality {
  fast,
  balanced,
  high,
  ultra;

  static Future<ResampleQuality> default_() =>
      StellatuneApi.instance.api.crateApiPlayerTypesResampleQualityDefault();
}

class SourceCatalogTypeDescriptor {
  final String pluginId;
  final String pluginName;
  final String typeId;
  final String displayName;

  const SourceCatalogTypeDescriptor({
    required this.pluginId,
    required this.pluginName,
    required this.typeId,
    required this.displayName,
  });

  @override
  int get hashCode =>
      pluginId.hashCode ^
      pluginName.hashCode ^
      typeId.hashCode ^
      displayName.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SourceCatalogTypeDescriptor &&
          runtimeType == other.runtimeType &&
          pluginId == other.pluginId &&
          pluginName == other.pluginName &&
          typeId == other.typeId &&
          displayName == other.displayName;
}

class TrackDecodeInfo {
  final int sampleRate;
  final int channels;
  final BigInt? durationMs;
  final String? metadataJson;
  final String? decoderPluginId;
  final String? decoderTypeId;

  const TrackDecodeInfo({
    required this.sampleRate,
    required this.channels,
    this.durationMs,
    this.metadataJson,
    this.decoderPluginId,
    this.decoderTypeId,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^
      channels.hashCode ^
      durationMs.hashCode ^
      metadataJson.hashCode ^
      decoderPluginId.hashCode ^
      decoderTypeId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TrackDecodeInfo &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          durationMs == other.durationMs &&
          metadataJson == other.metadataJson &&
          decoderPluginId == other.decoderPluginId &&
          decoderTypeId == other.decoderTypeId;
}

class TranscodeProgressEvent {
  final String phase;
  final String? message;
  final String? sourcePath;
  final String? outputPath;
  final BigInt processedFrames;
  final BigInt? totalFrames;
  final BigInt writtenBytes;
  final int? sampleRate;
  final int? channels;
  final BigInt? elapsedMs;

  const TranscodeProgressEvent({
    required this.phase,
    this.message,
    this.sourcePath,
    this.outputPath,
    required this.processedFrames,
    this.totalFrames,
    required this.writtenBytes,
    this.sampleRate,
    this.channels,
    this.elapsedMs,
  });

  @override
  int get hashCode =>
      phase.hashCode ^
      message.hashCode ^
      sourcePath.hashCode ^
      outputPath.hashCode ^
      processedFrames.hashCode ^
      totalFrames.hashCode ^
      writtenBytes.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      elapsedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TranscodeProgressEvent &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          message == other.message &&
          sourcePath == other.sourcePath &&
          outputPath == other.outputPath &&
          processedFrames == other.processedFrames &&
          totalFrames == other.totalFrames &&
          writtenBytes == other.writtenBytes &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          elapsedMs == other.elapsedMs;
}
