[package]
name = "stellatune-audio"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
crossbeam-channel.workspace = true
tokio.workspace = true
rubato.workspace = true
audioadapter-buffers.workspace = true
thiserror.workspace = true

stellatune-audio-core.workspace = true
lattice-actor.workspace = true

[target.'cfg(windows)'.dependencies]
windows.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
libc.workspace = true

[lints]
workspace = true
