[package]
name = "stellatune-library"
version = "0.1.0"
edition = "2024"
license.workspace = true

[dependencies]
stellatune-media-probe.workspace = true
anyhow.workspace = true
crossbeam-channel.workspace = true
sqlx.workspace = true
tokio.workspace = true
tracing.workspace = true
walkdir.workspace = true
symphonia.workspace = true
notify.workspace = true
serde.workspace = true
async-trait.workspace = true
flutter_rust_bridge.workspace = true

lattice-actor.workspace = true
serde_json.workspace = true
base64.workspace = true
encoding_rs = "0.8"
chardetng = "0.1"
stellatune-audio-core = { path = "../stellatune-audio-core" }

[lints]
workspace = true

[dev-dependencies]
tempfile.workspace = true
